### ISSUE TITLE
Programmatic usage.

### ISSUE THREAD

**Issue by VictorioBerra** [seejohnrun/haste-server#100]
I would like to use this haste server in my program. I need the ability to start and stop it on demand.

Currently, the only usage for this module is to install it and run node server.js or npm start.

I believe this project could benefit from having a /bin/ folder and a binary that kicks off the server, AND an index.js that exposes a simple start/stop/restart API for the project so I can require('haste').start(options)

**Comment by Logic-gate** [comment]
You could write an init script(or systemd equivalent). Make sure to specify the exact steps; i.e. redis-server on default port for example, npm start. And also make sure to stop said services cleanly. You should also add a port checker, something like `netstat -tulpn | grep :$PORT` before starting to avoid startup failure.
