### ISSUE TITLE
I regularly get ApplicationErrors

### ISSUE THREAD

**Issue by FichteFoll** [seejohnrun/haste-server#101]
I use https://github.com/nicetrysean/SublimeToHastebin to upload snippets, but often times when I access the url of the generated snippet I get an ApplicationError from the site.

It usually goes away after some time or when I change the extension in the url manually to e.g. `txt`.

It didn't use to be like that.

**Comment by Dasoren** [comment]
I am getting this same error, it has to do with highlight.mini.js I believe.

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
