### ISSUE TITLE
RFE: ability to specify configuration file

### ISSUE THREAD

**Issue by gangelop** [seejohnrun/haste-server#105]
Hello,

I would like to have the ability to specify the configuration file path instead of using `config.js` in the working directory. Looking very briefly into `server.js` it appears that it just looks for this specific file and there is no option to set a different file. Hopefully, I didn't miss something.

Cheers, and thanks for an amazing project!

**Comment by Logic-gate** [comment]
As of now, there is no option to specify the config file via system arguments. It needs to be defined in `server.js`. You could manually set the path of your new `config.js` by defining it in `server.js`. I doubt that this will be added; do you have a use-case that may shed light on it's validity?

**Comment by lathan** [comment]
I was trying to figure out how to streamline the deployment and it just didn't make sense to place the config file in the same dir with the code. Then again, I'm not familiar with deploying npm-based things. I've settled for putting everything somewhere in `/opt/` and managing the whole thing with ansible.

**Comment by lathan** [comment]
Thanks for the info. Just to clarify, this isn't high priority for me at the moment. Only have one instance with very few users.

**Comment by Logic-gate** [comment]
No worries, will keep this open until further notice. tc.
