### ISSUE TITLE
How can I modify init script for no root start?

### ISSUE THREAD

**Issue by simpleuser99** [seejohnrun/haste-server#107]
Hello/
This https://github.com/seejohnrun/haste-server/wiki/init.d-script-for-haste-server/8e7ed805d6adb4152123187836c1e33d56b1f9d6 script to run application from user root. How can I modify init script that application run from no root user?

**Comment by Logic-gate** [comment]
Could you elaborate further? 

Is this a general system question or specific to haste? as in, are you having trouble with file permissions?
