### ISSUE TITLE
Recognise diff's

### ISSUE THREAD

**Issue by Justinzobel** [seejohnrun/haste-server#108]
http://hastebin.com/agiqamocub.coffee for instance

Would be nice to have a cleaner way to read diffs like with green +'s and red -'s etc, maybe like the raw mode, a diff mode.

**Comment by seejohnrun** [comment]
Try the `.diff` extension: http://hastebin.com/nanegamesi.diff

**Comment by akien-mga** [comment]
Is there any way hastebin could automatically use this `.diff` extension when recognizing a unified diff?
I've been using hastebin for more than a year without knowing of this feature, and just found out diff formatting exists as I was about to open a feature request :)

**Comment by akien-mga** [comment]
(Actually I realize now that one can change the extension to pick the formatting wanted, not only for diffs but for any recognized format... I believe that feature could use some documentation e.g. in the `about.md` -- which btw no longer shows up on hastebin.com, but that's a different topic)

**Comment by seejohnrun** [comment]
Yeah you can change the extension - the auto-detection tries its best but isn't perfect and makes mistakes especially on shorter documents.

Would be a good addition to the README though, and there's a separate issue indeed that I'll have a PR for soon
