### ISSUE TITLE
Can't start the server!

### ISSUE THREAD

**Issue by Delivator** [seejohnrun/haste-server#110]
Windows 10 Pro x64
Node v4.4.0 LTS (Basic installation)
Default config

Console outputs:
npm install => http://hastebin.com/epewahutuq

node server.js => http://hastebin.com/mipodidesi
npm start => http://hastebin.com/uhobufiqal

Can someone help me please?

**Comment by jangrewe** [comment]
npm install

**Comment by Logic-gate** [comment]
Could you please repost the logs, only the last one is visible.

From the last one, it seems that you dont have `redis-server`.

**Comment by seejohnrun** [comment]
Definitely agree (and just updated the docs).
You need `redis-server` installed to run hastebin, or you can use the `file` config option
