### ISSUE TITLE
Code is not displayed in iOS Safari

### ISSUE THREAD

**Issue by a1ip** [seejohnrun/haste-server#111]
Code saved on site hasten.com is not displayed in iOS Safari

**Comment by Logic-gate** [comment]
What do you mean? I tested it, it works. It could be that the paste has expired. If so, it will not show up anywhere.

**Comment by Logic-gate** [comment]
I think this was the result of an expired paste.

If you are running you own instance of haste-server, under the `storage` option in `config.js` change `expire` value to any duration you want.

Note, that hastebin.com stores pastes for a maximum of 30 days, then it deletes it.

If this is the case, please create a new issue.
