### ISSUE TITLE
Support drag and drop (possibly of multiple files)

### ISSUE THREAD

**Issue by ionas** [seejohnrun/haste-server#119]
In the sense of imgur for text-files:
Refs:
- http://puphpet.com/ (drag and drop config.yaml)
- http://imgur.com/ (drag and drop of 1-n img files)

**Comment by ionas** [comment]
My use case was: share 10 migration files (think rails or phinx migrations) alongside a git PR.

**Comment by ionas** [comment]
My use case was: share 10 migration files (think rails or phinx migrations) alongside a git PR.

**Comment by ionas** [comment]
My use case was: share 10 migration files (think rails or phinx migrations) alongside a git PR.

**Comment by Logic-gate** [comment]
Wouldn't piping the files make more sense?
Check https://github.com/seejohnrun/haste-client.

**Comment by seejohnrun** [comment]
This is cool, but like @Logic-gate mentions, probably an easier solution is to pipe the files you need into a utility like `haste`.
