### ISSUE TITLE
Haste-Server NGINX 

### ISSUE THREAD

**Issue by GabeHirakawa** [seejohnrun/haste-server#126]
I have tried and tried. The Haste-server running on paste.stealthgus.tech:7777 works perfectly fine, but as soon as I turn on a proxy, it dies. I've searched high and low for the answer but it all seems to be centralized around location / parameter.  When changing this to something such as /about.md (just for testing) it brings me to the default NGINX page. Any help would be greatly appreciated. My config is below.

http://hastebin.com/aduvuhiyiv.nginx

**Comment by Logic-gate** [comment]
Okay, this solution is for apache; I dont have much experience with Nginx..but I hope it will help you in some way.

add `/` at the end. 
`proxy_pass         "http://localhost:7777/";`

In apache it looks like this:
`ProxyPass / http://localhost:7777/`

Also try and add Nginx's equivalent of `ProxyPassReverse`

**Comment by seejohnrun** [comment]
Closing this now, and thanks @Logic-gate
