### ISSUE TITLE
npm start don't work (throw callback_err;)

### ISSUE THREAD

**Issue by com002** [seejohnrun/haste-server#128]
`root@com002:/var/www/sub/hb# npm start

> haste@0.1.0 start /var/www/sub/hb
> node server.js

info: configuring redis
info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md
info: listening on 0.0.0.0:7777
/var/www/sub/hb/node_modules/redis/index.js:504
                throw callback_err;
                ^

Error: Ready check failed: NOAUTH Authentication required.
    at RedisClient.on_info_cmd (/var/www/sub/hb/node_modules/redis/index.js:317:35)
    at Command.callback (/var/www/sub/hb/node_modules/redis/index.js:365:14)
    at RedisClient.return_error (/var/www/sub/hb/node_modules/redis/index.js:500:25)
    at ReplyParser.<anonymous> (/var/www/sub/hb/node_modules/redis/index.js:260:14)
    at emitOne (events.js:77:13)
    at ReplyParser.emit (events.js:169:7)
    at ReplyParser.send_error (/var/www/sub/hb/node_modules/redis/lib/parser/javascript.js:279:10)
    at ReplyParser.execute (/var/www/sub/hb/node_modules/redis/lib/parser/javascript.js:162:22)
    at RedisClient.on_data (/var/www/sub/hb/node_modules/redis/index.js:476:27)
    at Socket.<anonymous> (/var/www/sub/hb/node_modules/redis/index.js:79:14)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs haste
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sub/hb/npm-debug.log
root@com002:/var/www/sub/hb#
`

npm-debug.log
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart haste@0.1.0
6 info start haste@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info haste@0.1.0 Failed to exec start script
9 verbose stack Error: haste@0.1.0 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid haste@0.1.0
11 verbose cwd /var/www/sub/hb
12 error Linux 3.16.0-4-amd64
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error haste@0.1.0 start: `node server.js`
17 error Exit status 1
18 error Failed at the haste@0.1.0 start script 'node server.js'.
18 error This is most likely a problem with the haste package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs haste
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls haste
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by Logic-gate** [comment]
Please paste your storage settings form `config.js`  
Plus, what happens when you run `redis-server`?

**Comment by seejohnrun** [comment]
Yeah this definitely looks like a special redis setup you have - you need to provide auth details in the config if they're required.  Re-open if you're still experiencing an issue
