### ISSUE TITLE
hastebin.com error!

### ISSUE THREAD

**Issue by POOPDAWG** [seejohnrun/haste-server#130]
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

plz help i have some important pastes

**Comment by POOPDAWG** [comment]
is everyone dead

**Comment by Wohlstand** [comment]
I'm alive! (But owner of the repo seems left stuff without maintenance)

**Comment by Logic-gate** [comment]
The latest commit was 2 days ago...so no, the project is not dead. @POOPDAWG it could be that server went down for a bit.

**Comment by seejohnrun** [comment]
I hope this isn't something you're still experiencing @POOPDAWG 
Seems to be working okay for me - but there are occasional outages as a result of me running this by myself with my own limited budget

**Comment by Mas21TheFag** [comment]
The service is still dead for me!
