### ISSUE TITLE
Not work in firefox

### ISSUE THREAD

**Issue by dimti** [seejohnrun/haste-server#134]
You need open this in Firefox
http://paste.wpstudio.ru/luzanekeko

Sceenshot: http://i.imgur.com/3B5ZyhT.png

How to fix it from sources or me need waiting update from developers?

**Comment by Wohlstand** [comment]
Toggle charset into UTF-8, and will work. On server is required forcing to use UTF-8 page encoding. Otherwise every user required to toggle UTF-8 manually

**Comment by dimti** [comment]
Im insert into index html

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

That works. Thanks

**Comment by dimti** [comment]
May be need add this string into indexhtml in our repo permanently?

**Comment by Wohlstand** [comment]
for HTML5 this would be better:
```html
<meta charset="utf-8" /> 
```

**Comment by Wohlstand** [comment]
@dimti , Author finally mergded fix, so, this can be closed

**Comment by Logic-gate** [comment]
@dimti @Wohlstand The change has been made. Thank you for shedding light on this. I am closing this issue. Cheers
