### ISSUE TITLE
Can't access any paste nor readme.md

### ISSUE THREAD

**Issue by KingDuckZ** [seejohnrun/haste-server#139]
Probably a consequence of the patch suggested in issue #53:

1. I access myhost.com/haste and I get the hastebin page
2. I input some text
3. I press the "save" button
4. pasted text appears in the browser as expected
5. I refresh the page and I get the home page again
6. I paste the address of the newly created paste but I still get redirected to the home page

The same happens if I try to access about.md. On the server I get:

```
nov 15 21:58:06 alarmpi2 systemd[1]: Started Simple and secure temporary file storage.
nov 15 21:58:12 alarmpi2 node[12773]: info: configuring redis
nov 15 21:58:16 alarmpi2 node[12773]: info: compressed application.js into application.min.js
nov 15 21:58:16 alarmpi2 node[12773]: info: loading static document name=about, path=./about.md
nov 15 21:58:16 alarmpi2 node[12773]: info: listening on 0.0.0.0:7777
nov 15 21:58:16 alarmpi2 node[12773]: info: connected to redis on 192.168.3.9:6379/3
nov 15 21:58:16 alarmpi2 node[12773]: debug: loaded static document success=true
nov 15 21:58:27 alarmpi2 node[12773]: verbose: added document key=owajigoviv
nov 15 21:58:32 alarmpi2 node[12773]: warn: document not found key=undefined
```

**Comment by asabla** [comment]
Seems like your missing some post data from the uri (e.g: nov 15 21:58:32 alarmpi2 node[12773]: warn: document not found key=undefined).

Do you have a proxy in front of the hastebin service? If that is the case, what are your current settings?

**Comment by KingDuckZ** [comment]
Yes I have nginx on a different server set up as described in #53. Pull request #140 fixes the problem for me, if I still use the nginx configuration suggested in #53.

**Comment by Logic-gate** [comment]
Added proxy instructions in [wiki](https://github.com/seejohnrun/haste-server/wiki/Installation) from http://www.ctrl-alt-del.cc/2014/11/haste-server-base-url-hackpatch.html. 

Closing issue.
