### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by Duckbuster** [seejohnrun/haste-server#151]
Cloned the repo and tried to run it, got this error.

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@2.15.11
> 3 info using node@v4.8.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart haste@0.1.0
> 6 info start haste@0.1.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info haste@0.1.0 Failed to exec start script
> 9 verbose stack Error: haste@0.1.0 start: `node server.js`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:854:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
> 10 verbose pkgid haste@0.1.0
> 11 verbose cwd /home/duckbuster/git/haste-server
> 12 error Linux 4.5.5-x86_64-linode69
> 13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 14 error node v4.8.0
> 15 error npm  v2.15.11
> 16 error code ELIFECYCLE
> 17 error haste@0.1.0 start: `node server.js`
> 17 error Exit status 1
> 18 error Failed at the haste@0.1.0 start script 'node server.js'.
> 18 error This is most likely a problem with the haste package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     node server.js
> 18 error You can get information on how to open an issue for this project with:
> 18 error     npm bugs haste
> 18 error Or if that isn't available, you can get their info via:
> 18 error
> 18 error     npm owner ls haste
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

**Comment by Logic-gate** [comment]
Mind sharing your storage settings in `config.js`

**Comment by Duckbuster** [comment]
It's the default:

>   "storage": {
>     "type": "redis",
>     "host": "0.0.0.0",
>     "port": 6379,
>     "db": 2,
>     "expire": 2592000
>   },

**Comment by Logic-gate** [comment]
I am assuming you have `redis` running. `npm install redis` or you have`redis-server` via your repo.

**Comment by Logic-gate** [comment]
Also, the output looks like it came from `npm-debug.log` right? mind sharing the exact output when you run`npm start`

**Comment by Duckbuster** [comment]
> > haste@0.1.0 start /home/duckbuster/git/haste-server 
> > node server.js 
>  
> info: configuring redis 
> info: compressed application.js into application.min.js 
> info: loading static document name=about, path=./about.md 
> info: listening on 127.0.0.1:8888 
> error: error connecting to redis index 2 error=Redis connection to 0.0.0.0:6379 failed - connect ECONNREFUSED 0.0.0.0:6379 
>  
> npm ERR! Linux 4.5.5-x86_64-linode69 
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" 
> npm ERR! node v4.8.0 
> npm ERR! npm  v2.15.11 
> npm ERR! code ELIFECYCLE 
> npm ERR! haste@0.1.0 start: `node server.js` 
> npm ERR! Exit status 1 
> npm ERR! 
> npm ERR! Failed at the haste@0.1.0 start script 'node server.js'. 
> npm ERR! This is most likely a problem with the haste package, 
> npm ERR! not with npm itself. 
> npm ERR! Tell the author that this fails on your system: 
> npm ERR!     node server.js 
> npm ERR! You can get information on how to open an issue for this project with: 
> npm ERR!     npm bugs haste 
> npm ERR! Or if that isn't available, you can get their info via: 
> npm ERR! 
> npm ERR!     npm owner ls haste 
> npm ERR! There is likely additional logging output above. 
>  
> npm ERR! Please include the following file with any support request: 
> npm ERR!     /home/duckbuster/git/haste-server/npm-debug.log 
>

**Comment by Duckbuster** [comment]
Oh ok I'm stupid, now I see my error. Needed to run redis

**Comment by Logic-gate** [comment]
Yup. this issue is more common than you imagine. No worries. Just report back when it works or if you need assistance.

**Comment by Duckbuster** [comment]
It works fine. Thanks for your help.

**Comment by Logic-gate** [comment]
Great. Glad I was of help to you. 

Cheers.
