### ISSUE TITLE
I have a error with start!

### ISSUE THREAD

**Issue by jimmy-rich** [seejohnrun/haste-server#152]
Hello, 
I have this error with start
root@4512d:/home/haste-server# npm start

> haste@0.1.0 start /home/haste-server
> node server.js

npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/haste-server
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/haste-server/npm-debug.log
npm ERR! not ok code 0

Thanks you

**Comment by seejohnrun** [comment]
You need a more modern version of node I believe
How are you installing this?

**Comment by jimmy57000** [comment]
I made an update and now it works!
Do you know how I could put an HTTPS?

Thanks !!

**Comment by seejohnrun** [comment]
I run https on hastebin.com through cloudflare. Very easy to set up, highly
recommend

**Comment by VAdamec** [comment]
Or just simply put it behind proxy - nging/apache/haproxy.

**Comment by Logic-gate** [comment]
@jimmy-rich Have a look at https://letsencrypt.org/ pretty straightforward

**Comment by Logic-gate** [comment]
@jimmy-rich is your issue resolved? if so. Please close it.
