### ISSUE TITLE
expiration?

### ISSUE THREAD

**Issue by Rhodesia** [seejohnrun/haste-server#153]
if i remove the expire param from the config keys wont expire right? What about keys that have been previously entered into the database?

**Comment by Logic-gate** [comment]
Yes, removing the expire param will keep key indefinitely. 
For keys saved with the expire param option, I think it best if you head to the redis documentation for the expire command https://redis.io/commands/expire#appendix-redis-expires as I am not sure what is the adequate command, although https://redis.io/commands/persist seems right.

```
redis> SET mykey "Hello"
"OK"
redis> EXPIRE mykey 10
(integer) 1
redis> TTL mykey
(integer) 10
redis> PERSIST mykey
(integer) 1
redis> TTL mykey
(integer) -1
redis> 
` ``
