### ISSUE TITLE
hastebin.com is down

### ISSUE THREAD

**Issue by v0idst4r** [seejohnrun/haste-server#161]
Edit: according to @seejohnrun www.hastebin.com up but hastebin.com isn't, for now you'll just have to use the www subdomain

**Comment by seejohnrun** [comment]
This appears to be at our CDN - will update when it's back

**Comment by seejohnrun** [comment]
also oddly https://www.hastebin.com/ seems to be up so it looks like something to do with DNS should keep you moving in the meantime

**Comment by kensoh** [comment]
Thanks @v0idst4r for raising and @seejohnrun for your update! Haste and hastebin.com is a really cool project. I recently integrated with it for my [web automation](https://github.com/tebelorg/TagUI) tool and notice it to be done last few days.

Also emailed to your gmail and Brian to say thanks for bringing such a cool project into reality. Like that you made the tool really easy to use and even include a CLI helper. The minimalist interface is superb.

**Comment by v0idst4r** [comment]
I don't know if it has to do with the DNS, after waiting eventually cloudflare will show a 502 bas gateway error and say it's the hosts problem. http://imgur.com/a/qthj7

**Comment by seejohnrun** [comment]
Yep agree - I'm looking more into it

**Comment by seejohnrun** [comment]
This should now be resolved - thanks! and let me know if not

**Comment by kensoh** [comment]
Thanks @seejohnrun ! Works for me :smile:

**Comment by ShalokShalom** [comment]
It is down again, since 5 days.

**Comment by MisterFixx** [comment]
Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

**Comment by bschley** [comment]
Where is the problem with hastebin.com? Hastebin.com is working now.. but sometimes the save button is not working during the week.

Do you need help to maintain hastebin.com?
