### ISSUE TITLE
Redis via socket

### ISSUE THREAD

**Issue by heyarne** [seejohnrun/haste-server#162]
Hi there,
I have redis running locally and listening over a socket at `/path/to/redis.sock`. How would I have to configure reids storage in order for this to work? Thanks in advance!

**Comment by seejohnrun** [comment]
The options in the config get passed directly to `node-redis`, so you should be able to provide any options they allow.  It looks like the `url` option may be the one you're looking for but I've never set up node-redis with a socket connection to redis so I'm not 100% sure.

Feel free to report back here to help others!
