### ISSUE TITLE
Typo in README.md: recompressStatisAssets 

### ISSUE THREAD

**Issue by jglopez** [seejohnrun/haste-server#165]
The variable `recompressStaticAssets` within [README.md](https://github.com/seejohnrun/haste-server/blob/344d1fec7b369541039782d7ab8c0be520b3f4c2/README.md#settings) is misspelled as `recompressStatisAssets` 

I verified this is likely not a typo by double-checking  `recompressStaticAssets` at: 
https://github.com/seejohnrun/haste-server/blob/master/config.js#L12

**Comment by seejohnrun** [comment]
Thanks!
