### ISSUE TITLE
Config resetting

### ISSUE THREAD

**Issue by vpn** [seejohnrun/haste-server#166]
I am unsure why the configuration file, `config.js`, keeps resetting to it's default values.
This occurs when, 
I have started the instance, using `npm start`, and there is a document retrieved. If I then stop the instance, using `ctrl + c`, and then start it again, the config file resets. Below is an image showing this.
![Terminal Session](http://i.stuf.io/350bzu9q15e15e5e5.png)

This hasn't happened on any other machine that I have set this up on before.
Any help would be appreciated.

**Comment by seejohnrun** [comment]
Resets meaning that the file reverts to what it was previously? If so, I've definitely never seen that before.  Are you operating the server directly from a `git` directory?  Some more detail about your setup might be helpful.  Thanks!

**Comment by vpn** [comment]
This was due to a mistake in my git setup, sorry about this.

Thanks
