### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by mememaestro** [seejohnrun/haste-server#167]
I'm pressing CTRL+n , but i'm getting nothing :(
Same with other shortcuts
I use Chrome  60.0.3112.101 (JS is enabled and everything else is ok)

**Comment by seejohnrun** [comment]
Weird this is working fine for me on hastebin.com - what OS are you on?

**Comment by mememaestro** [comment]
Windows 10
I use Hastebin.com

**Comment by mememaestro** [comment]
Lol. I disabled my adblocker and everything is ok, but it work like in #143
