### ISSUE TITLE
Need support for raw access

### ISSUE THREAD

**Issue by mathuin** [seejohnrun/haste-server#169]
GitHub has this thing where I can look at a file and press a 'Raw' button and get just the raw content without processing or Javascript or anything.  It would be nice to have access to hastebin content in the raw.  https://raw.githubusercontent.com/seejohnrun/haste-server/master/README.md is an example of raw content, and while I don't think using a different hostname is necessarily the right choice, having something like https://hastebin.com/jexemitici?raw=1 or the like might be awesome.  Bonus points if the user agent is detected so folks who wget/curl documents from haste servers get what they expect and not Javascript!

**Comment by seejohnrun** [comment]
Thanks!

This already exists at https://hastebin.com/raw/inudutiyaz

I do like the idea of user-agent detection, but it seems a bit too magic to me
