### ISSUE TITLE
Doesn't detect C# properly, and when it does the syntax hightlighting is incorrect

### ISSUE THREAD

**Issue by TAGC** [seejohnrun/haste-server#170]
I've pasted a number of C# code snippets into hastebin and more often than not it doesn't detect it as the correct language and so applies the wrong syntax highlighting. [Here's an example](https://hastebin.com/ibodufaneg.cpp).

From #89, @moomoohk commented:

> The extension in the URL is what determines the syntax highlighting. If the automatic prediction is wrong you can just override it yourself.

(FWIW @Logic-gate said he'd add a note about this to the README and I don't see one, so that's a small issue in itself)

Based on this, I tried changing the extension from .cpp to .cs ([link](https://hastebin.com/ibodufaneg.cs)) and that resulted in no syntax highlighting being applied at all:

<img width="1280" alt="screen shot 2017-09-28 at 23 44 12" src="https://user-images.githubusercontent.com/1588951/30993453-0635f59e-a4a7-11e7-8fbe-e76eeb4fd0b2.png">

In case that hastebin gets removed, I'll copy it below:

```cs
using System;
using System.Collections.Generic;
using System.IO;

namespace experiment
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = new Fraction(1, 3);
            var y = new Fraction(3, 5);
            var comparer = new StandardFractionComparer();

            switch (comparer.Compare(x, y))
            {
                case -1:
                    Console.WriteLine($"{x} < {y}");
                    break;

                case 0:
                    Console.WriteLine($"{x} = {y}");
                    break;

                case 1:
                    Console.WriteLine($"{x} > {y}");
                    break;
            }
        }
    }

    class Fraction
    {
        public Fraction(int numerator, int denominator)
        {
            Numerator = numerator;
            Denominator = denominator;
        }

        public int Numerator { get; }
        public int Denominator { get; }

        public override string ToString() => $"{Numerator}/{Denominator}";
    }

    class StandardFractionComparer : Comparer<Fraction>
    {
        public override int Compare(Fraction x, Fraction y)
        {
            double AsDouble(Fraction f) => (double)f.Numerator / f.Denominator;
            return AsDouble(x).CompareTo(AsDouble(y));
        }
    }
}
```

**Comment by moomoohk** [comment]
Hey :)
Got pinged from the other thread, figured I'd try to help out here
Not too familiar with the structure of this project but I had a look at `application.js` and everything there looked fine. I debugged the `hljs` function that gets called with the `cs` language and found a masked exception:

    Error: Illegal lexeme "<" for mode "<unnamed>"
        at m (highlight.min.js:formatted:248)
        at Object.l [as highlight] (highlight.min.js:formatted:267)
        at Object.success (application.min.js:formatted:21)
        at n (jquery.min.js:2)
        at Object.fireWith [as resolveWith] (jquery.min.js:2)
        at w (jquery.min.js:4)
        at XMLHttpRequest.d (jquery.min.js:4)

Turns out the version of `hljs` this project depends on doesn't like classes that extend from generic parents. Specifically if I change `Comparer<Fraction>` on line 46 to `Comparer` everything seems to highlight just fine! Check it out: https://hastebin.com/gazufepaso.cs

I also checked out the `hljs` repo and looks like there's already an issue open there for this problem, go +1 it https://github.com/isagalaev/highlight.js/issues/1424

Hope this helped

**Comment by TAGC** [comment]
Interesting, Discord apparently uses highlight.js for syntax highlighting and has no issues with generic classes/interfaces:

![discord_2017-09-30_21-37-07](https://user-images.githubusercontent.com/1588951/31049264-9cc7caba-a627-11e7-82be-d247a4e0c144.png)

I'll mention this over there.

**Comment by seejohnrun** [comment]
Could be that we just need to upgrade highlight.js - right?

**Comment by moomoohk** [comment]
Looks as though the issue I linked is still open so I'm not sure upgrading would fix the problem. Check what Discord did to solve the problem could be worth it

**Comment by seejohnrun** [comment]
This has been fixed in highlight JS and I'll reference the PR to upgrade in a minute
