### ISSUE TITLE
Error after port change

### ISSUE THREAD

**Issue by Perflyst** [seejohnrun/haste-server#172]
If i change the port the haste server dont start anymore:
I changed it to Port 77 in the config.js and in the vhost apache2.

> haste@0.1.0 start /home/user/haste-server
> node server.js

info: configuring redis
info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md
info: listening on 0.0.0.0:77

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/user/haste-server
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/haste-server/npm-debug.log
npm ERR! not ok code 0

**Comment by seejohnrun** [comment]
Ports under 1024 require `sudo` privilege in order to run

**Comment by Perflyst** [comment]
Dont work with sudo, same error

**Comment by seejohnrun** [comment]
Sorry I mis-wrote, it would need to be run as `root`.  Read more here: https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux
