### ISSUE TITLE
POST API - 404

### ISSUE THREAD

**Issue by jasoryeh** [seejohnrun/haste-server#177]
In the wiki it says to post to /document
![image](https://user-images.githubusercontent.com/13290941/31980708-35104296-b903-11e7-9861-81abc91a2ded.png)
However, on my server, and hastebin.com, they all give a 404
![image](https://user-images.githubusercontent.com/13290941/31980734-69c8939e-b903-11e7-9a29-e52fbe1f8ac5.png)
Which makes me unable to send post requests.
Tested using PostMan, Chrome and inside my Java Application.

**Comment by seejohnrun** [comment]
There's a typo in your above code.  `POST` goes to `documents`, not `document`.
