### ISSUE TITLE
Size limit at hastebin.com ?

### ISSUE THREAD

**Issue by hanxue** [seejohnrun/haste-server#182]
When I post output from `curl` to hastebin.com, I got a `400: Bad Request`. The curl output is about 500K in size

See video capture at https://asciinema.org/a/PLJ0p1QPnbCqZ4yJTC8SjrAmm

Smaller sized output is working fine, e.g. https://hastebin.com/avuzawuzuy

Is there a size limit for hastebin, and what is it?

**Comment by seejohnrun** [comment]
👋 https://github.com/seejohnrun/haste-server/blob/master/config.js#L8
