### ISSUE TITLE
haste-server crashing randomly with the following error

### ISSUE THREAD

**Issue by cortex3** [seejohnrun/haste-server#185]
`Nov 23 11:04:25 server_name pastebin[17021]: /opt/haste-server/node_modules/st/st.js:585
Nov 23 11:04:25 server_name pastebin[17021]: throw new Error('This should not ever happen')
Nov 23 11:04:25 server_name pastebin[17021]: ^
Nov 23 11:04:25 server_name pastebin[17021]: Error: This should not ever happen
Nov 23 11:04:25 server_name pastebin[17021]: at Mount._loadContent (/opt/haste-server/     node_modules/st/st.js:585:9)
Nov 23 11:04:25 server_name pastebin[17021]: at AsyncCache.get (/opt/haste-server/         node_modules/async-cache/ac.js:58:8)
Nov 23 11:04:25 server_name pastebin[17021]: at Mount.cachedFile (/opt/haste-server/       node_modules/st/st.js:388:22)
Nov 23 11:04:25 server_name pastebin[17021]: at Mount.file (/opt/haste-server/node_modules/st/st.js:378:10)
Nov 23 11:04:25 server_name pastebin[17021]: at Mount.<anonymous> (/opt/haste-server/      node_modules/st/st.js:314:16)
Nov 23 11:04:25 server_name pastebin[17021]: at /opt/haste-server/node_modules/async-cache/ac.js:71:7
Nov 23 11:04:25 server_name pastebin[17021]: at Array.forEach (native)
Nov 23 11:04:25 server_name pastebin[17021]: at AsyncCache.<anonymous> (/opt/haste-server/ node_modules/async-cache/ac.js:70:9)
Nov 23 11:04:25 server_name pastebin[17021]: at Mount.<anonymous> (/opt/haste-server/      node_modules/st/st.js:574:7)
Nov 23 11:04:25 server_name pastebin[17021]: at /opt/haste-server/node_modules/graceful-fs/polyfills.js:287:18
Nov 23 11:04:25 server_name systemd[1]: pastebin.service: main process exited,             code=exited, status=1/FAILURE
Nov 23 11:04:25 server_name systemd[1]: Unit pastebin.service entered failed state.
Nov 23 11:04:25 server_name systemd[1]: pastebin.service failed. `

simply starting the service again fixes this issue for a couple days. 
The only changes to the haste-server files are the following changes in the config.js
`  "storage": {
   "path": "./data/",
   "type": "file"
  },
`
Sadly I don't have enough knowledge about node to debug this issue further.

**Comment by seejohnrun** [comment]
Odd - this is actually coming from one of our dependencies it looks like.

Have you modified anything else?

**Comment by PassTheMayo** [comment]
![image](https://user-images.githubusercontent.com/16949253/33800903-35a4e0e6-dd10-11e7-9505-fae21fdf5e38.png)

He says that he doesn't have enough Node knowledge, so I would assume not. @seejohnrun

**Comment by Logic-gate** [comment]
Wait, why is this even running as a .service? never liked systemd, anyways paste your daemon.service file.

**Comment by Acelection** [comment]
I've reinstalled the server to see if any of my changes caused the error but the problem still persists. This is the service file I'm using:

 `[Unit]
Description=Start haste-server pastebin

[Service]
User=pastebin
WorkingDirectory=/opt/haste-server
ExecStart=/usr/bin/node /opt/haste-server/server.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=pastebin
Restart=always
RestartSec=2

[Install]
WantedBy=mutli-user.target
`

**Comment by Wohlstand** [comment]
I'm also using haste-server through Systemd, and just now I have fetched a fresh source and tried to restart:
```
root@mail:~# service haste-server status
Redirecting to /bin/systemctl status haste-server.service
● haste-server.service - Hastebin Server
   Loaded: loaded (/usr/lib/systemd/system/haste-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Пн 2017-12-11 11:58:43 MSK; 8s ago
  Process: 5227 ExecStart=/Server/Server_Soft/haste-server/server.sh (code=exited, status=0/SUCCESS)
 Main PID: 5227 (code=exited, status=0/SUCCESS)

дек 11 11:58:43 mail.wohlnet.ru systemd[1]: haste-server.service holdoff time over, scheduling restart.
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: start request repeated too quickly for haste-server.service
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: Failed to start Hastebin Server.
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: Unit haste-server.service entered failed state.
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: haste-server.service failed.
```

```
root@mail:~# service haste-server status
Redirecting to /bin/systemctl status haste-server.service
● haste-server.service - Hastebin Server
   Loaded: loaded (/usr/lib/systemd/system/haste-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Пн 2017-12-11 11:58:43 MSK; 24s ago
  Process: 5227 ExecStart=/Server/Server_Soft/haste-server/server.sh (code=exited, status=0/SUCCESS)
 Main PID: 5227 (code=exited, status=0/SUCCESS)

дек 11 11:58:43 mail.wohlnet.ru systemd[1]: haste-server.service holdoff time over, scheduling restart.
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: start request repeated too quickly for haste-server.service
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: Failed to start Hastebin Server.
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: Unit haste-server.service entered failed state.
дек 11 11:58:43 mail.wohlnet.ru systemd[1]: haste-server.service failed.
root@mail:~# service haste-server stop
Redirecting to /bin/systemctl stop haste-server.service
```
Then I have tried to run haste-server manually under same user as systemd wants:
```
root@mail:~# su vitaly
vitaly@mail:/root$ /Server/Server_Soft/haste-server/server.sh
vitaly
info: configuring redis
/Server/Server_Soft/haste-server/server.js:65
      fs.writeFileSync('./static/' + dest, uglify.minify(orig_code).code, 'utf8');
                                                  ^

TypeError: uglify.minify is not a function
    at Object.<anonymous> (/Server/Server_Soft/haste-server/server.js:65:51)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
/Server/Server_Soft/haste-server/server.sh: line 10: cd: /root: Отказано в доступе
vitaly@mail:/root$
```

server.sh:
```bash
#!/bin/bash

whoami

BAK=$PWD
cd /Server/Server_Soft/haste-server

/usr/bin/node --max-old-space-size=256 ./server.js

cd $BAK
```

haste-server.service:
```ini
[Unit]
Description=Hastebin Server
Requires=redis.service
After=redis.service

[Service]
ExecStart=/Server/Server_Soft/haste-server/server.sh
Restart=always
RestartSec=10                       # Restart service after 10 seconds if node service crashes
StandardOutput=syslog               # Output to syslog
StandardError=syslog                # Output to syslog
SyslogIdentifier=haste-server
User=vitaly
Group=vitaly
Environment=NODE_ENV=hasteserver PORT=7777

[Install]
WantedBy=multi-user.target
```

**Comment by Wohlstand** [comment]
Okay, I got it running!
I just did `npm update` on the haste repo, and then haste server starts successfully!

**Comment by didyouexpectthat** [comment]
I run systemd, and I tried to npm update; it did not resolve my issue. 
On a fresh install of haste-server, I see the following....
```
systemd[1]: Starting haste.service...
systemd[1]: Started haste.service.
hastebin[14806]: info: compressed application.js into application.min.js
hastebin[14806]: info: loading static document name=about, path=./about.md
hastebin[14806]: /opt/haste-server/lib/key_generators/phonetic.js:13
hastebin[14806]: module.exports = class PhoneticKeyGenerator {
hastebin[14806]: ^^^^^
hastebin[14806]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
hastebin[14806]: at exports.runInThisContext (vm.js:53:16)
hastebin[14806]: at Module._compile (module.js:373:25)
hastebin[14806]: at Object.Module._extensions..js (module.js:416:10)
hastebin[14806]: at Module.load (module.js:343:32)
hastebin[14806]: at Function.Module._load (module.js:300:12)
hastebin[14806]: at Module.require (module.js:353:17)
hastebin[14806]: at require (internal/module.js:12:17)
hastebin[14806]: at Object.<anonymous> (/opt/haste-server/server.js:90:11)
hastebin[14806]: at Module._compile (module.js:409:26)
hastebin[14806]: at Object.Module._extensions..js (module.js:416:10)
systemd[1]: haste.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit haste.service entered failed state.
systemd[1]: haste.service holdoff time over, scheduling restart.
systemd[1]: Stopping haste.service...
systemd[1]: Starting haste.service...
systemd[1]: haste.service start request repeated too quickly, refusing to start.
systemd[1]: Failed to start haste.service.
systemd[1]: Unit haste.service entered failed state.
```

My service file is fairy straightforward and has never been problematic until I upgraded.
```
[Service]
ExecStart=/usr/bin/node /opt/haste-server/server.js
Restart=always
StandardOutput=syslog
SyslogIdentifier=hastebin
User=haste
WorkingDirectory=/opt/haste-server

[Install]
WantedBy=multi-user.target
```

**Comment by didyouexpectthat** [comment]
And on a fresh install of haste-server, I see:

```
systemd[1]: Starting haste.service...
systemd[1]: Started haste.service.
hastebin[22311]: info: compressed application.js into application.min.js
hastebin[22311]: info: loading static document name=about, path=./about.md
hastebin[22311]: /opt/haste-server/lib/key_generators/phonetic.js:13
hastebin[22311]: module.exports = class PhoneticKeyGenerator {
hastebin[22311]: ^^^^^
hastebin[22311]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
hastebin[22311]: at exports.runInThisContext (vm.js:53:16)
hastebin[22311]: at Module._compile (module.js:373:25)
hastebin[22311]: at Object.Module._extensions..js (module.js:416:10)
hastebin[22311]: at Module.load (module.js:343:32)
hastebin[22311]: at Function.Module._load (module.js:300:12)
hastebin[22311]: at Module.require (module.js:353:17)
hastebin[22311]: at require (internal/module.js:12:17)
hastebin[22311]: at Object.<anonymous> (/opt/haste-server/server.js:90:11)
hastebin[22311]: at Module._compile (module.js:409:26)
hastebin[22311]: at Object.Module._extensions..js (module.js:416:10)
systemd[1]: haste.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit haste.service entered failed state.
systemd[1]: haste.service holdoff time over, scheduling restart.
systemd[1]: Stopping haste.service...
```

**Comment by seejohnrun** [comment]
@didyouexpectthat Please update node it seems you're running an old version

**Comment by cortex3** [comment]
hi, just wanted to say that the problem still persists. I've changed the service file to minimize the service downtime. But it would still be cool if the problem was fixed. Here's the service file if anyone has the same problem. 

`[Unit]
Description=Start haste-server pastebin

[Service]
User=pastebin
WorkingDirectory=/opt/haste-server
ExecStart=/usr/bin/node /opt/haste-server/server.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=pastebin
Restart=always
RestartSec=2

[Install]
WantedBy=mutli-user.target
`

**Comment by C0rn3j** [comment]
```
node[34411]: /usr/lib/node_modules/haste/node_modules/st/st.js:585
node[34411]:   throw new Error('This should not ever happen')
node[34411]:   ^
node[34411]: Error: This should not ever happen
node[34411]:     at Mount._loadContent (/usr/lib/node_modules/haste/node_modules/st/st.js:585:9)
node[34411]:     at AsyncCache.get (/usr/lib/node_modules/haste/node_modules/async-cache/ac.js:58:8)
node[34411]:     at Mount.cachedFile (/usr/lib/node_modules/haste/node_modules/st/st.js:388:22)
node[34411]:     at Mount.file (/usr/lib/node_modules/haste/node_modules/st/st.js:378:10)
node[34411]:     at Mount.<anonymous> (/usr/lib/node_modules/haste/node_modules/st/st.js:314:16)
node[34411]:     at /usr/lib/node_modules/haste/node_modules/async-cache/ac.js:71:7
node[34411]:     at Array.forEach (<anonymous>)
node[34411]:     at AsyncCache.<anonymous> (/usr/lib/node_modules/haste/node_modules/async-cache/ac.js:70:9)
node[34411]:     at Mount.<anonymous> (/usr/lib/node_modules/haste/node_modules/st/st.js:574:7)
node[34411]:     at /usr/lib/node_modules/haste/node_modules/graceful-fs/polyfills.js:285:20
```
Still an issue in 2020. Using AUR/haste-server-git

**Comment by seejohnrun** [comment]
If this is still relevant it would be very helpful to have someone give it a shot on the latest `master`. I'm not sure how AUR `haste-server-git` works but maybe it's pulling directly from `master`.

The issue you're all seeing is very strange to me and is coming from inside of a dependency of ours `st`

**Comment by seejohnrun** [comment]
I'm going to close this for now due to the date, but please feel free to re-open if this is still happening to someone out there

**Comment by thetayloredman** [comment]
@seejohnrun Happened to me today, using `pm2` with `pm2 startup`

**Comment by C0rn3j** [comment]
Still happens with `5d2965f` - i.e. latest master.
```
13:51:20 bree node[64]: /usr/lib/node_modules/haste/node_modules/st/st.js:640
13:51:20 bree node[64]:     throw new Error('This should not ever happen')
13:51:20 bree node[64]:     ^
13:51:20 bree node[64]: Error: This should not ever happen
13:51:20 bree node[64]:     at Mount._loadContent (/usr/lib/node_modules/haste/node_modules/st/st.js:640:11)
13:51:20 bree node[64]:     at AsyncCache.get (/usr/lib/node_modules/haste/node_modules/async-cache/ac.js:63:8)
13:51:20 bree node[64]:     at Mount.cachedFile (/usr/lib/node_modules/haste/node_modules/st/st.js:419:24)
13:51:20 bree node[64]:     at Mount.file (/usr/lib/node_modules/haste/node_modules/st/st.js:409:12)
13:51:20 bree node[64]:     at /usr/lib/node_modules/haste/node_modules/st/st.js:342:18
13:51:20 bree node[64]:     at /usr/lib/node_modules/haste/node_modules/async-cache/ac.js:79:7
13:51:20 bree node[64]:     at Array.forEach (<anonymous>)
13:51:20 bree node[64]:     at AsyncCache.<anonymous> (/usr/lib/node_modules/haste/node_modules/async-cache/ac.js:78:9)
13:51:20 bree node[64]:     at /usr/lib/node_modules/haste/node_modules/st/st.js:629:9
13:51:20 bree node[64]:     at callback (/usr/lib/node_modules/haste/node_modules/graceful-fs/polyfills.js:299:20)
13:51:20 bree systemd[1]: haste-server.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by mimicdotga** [comment]
`
> haste@0.1.0 start /home/server/hastebin/haste-server
> node server.js

info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md
info: listening on 0.0.0.0:8080
verbose: retrieved document key=xcNh594yEr
verbose: retrieved document key=xcNh594yEr
verbose: retrieved document key=xcNh594yEr
verbose: retrieved document key=xcNh594yEr
verbose: retrieved document key=xcNh594yEr
/home/server/hastebin/haste-server/node_modules/st/st.js:640
    throw new Error('This should not ever happen')
    ^

Error: This should not ever happen
    at Mount._loadContent (/home/server/hastebin/haste-server/node_modules/st/st.js:640:11)
    at AsyncCache.get (/home/server/hastebin/haste-server/node_modules/async-cache/ac.js:63:8)
    at Mount.cachedFile (/home/server/hastebin/haste-server/node_modules/st/st.js:419:24)
    at Mount.file (/home/server/hastebin/haste-server/node_modules/st/st.js:409:12)
    at /home/server/hastebin/haste-server/node_modules/st/st.js:342:18
    at /home/server/hastebin/haste-server/node_modules/async-cache/ac.js:79:7
    at Array.forEach (<anonymous>)
    at AsyncCache.<anonymous> (/home/server/hastebin/haste-server/node_modules/async-cache/ac.js:78:9)
    at /home/server/hastebin/haste-server/node_modules/st/st.js:629:9
    at callback (/home/server/hastebin/haste-server/node_modules/graceful-fs/polyfills.js:295:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/server/.npm/_logs/2021-12-25T01_39_59_727Z-debug.log`
it happened randomly today, it never happened before
