### ISSUE TITLE
PostgreSQL error

### ISSUE THREAD

**Issue by Attoy** [seejohnrun/haste-server#186]
I installed HasteBin on my server and it works fine but as soon as I try to link it with my PostgreSQL it doesn't work anymore. I followed the installation instructions. Installed `npm install pg` and modified the `config.js` to reflect PostgreSQL changes:
```
{
  "type": "postgres",
  "connectionUrl": "postgres://myuser:mysupersecretpassword@localhost:5432/mydbname"
}
```
and when I try to start hastebin with `npm start` I receive the following error:

`error: error persisting value to postgres name=error, length=98, severity=ERROR, code=42501, detail=undefined, hint=undefined, position=undefined, internalPosition=undefined, internalQuery=undefined, where=undefined, schema=undefined, table=undefined, column=undefined, dataType=undefined, constraint=undefined, file=aclchk.c, line=3410, routine=aclcheck_error`

Any help on how I can fix it? My password contains special characters, could be that the issue?

**Comment by Logic-gate** [comment]
Did you create a table in you db?

**Comment by Attoy** [comment]
@Logic-gate Yes, as per instruction:
`create table entries (id serial primary key, key varchar(255) not null, value text not null, expiration int, unique(key));`

**Comment by Logic-gate** [comment]
Does your password contain quotes? and what postgres version are you on?

**Comment by Attoy** [comment]
No quotes but it contains @ % and &. Is it a problem?
PostgreSQL version 10

**Comment by Logic-gate** [comment]
Shouldn't be. Code 42501 is assigned to insufficient_privilege https://www.postgresql.org/docs/9.6/static/errcodes-appendix.html

**Comment by Logic-gate** [comment]
Try this, grant privileges to PUBLIC, as in everyone.

`GRANT SELECT ON tablename TO PUBLIC;`

**Comment by Attoy** [comment]
I'm pretty sure I gave "myuser" all privileges on the "mydbname"; I'll check in a bit as soon as I'm at home again. I'll post further information later. Thanks @Logic-gate

**Comment by Logic-gate** [comment]
@Attoy Okay, sure. cheers

**Comment by Attoy** [comment]
@Logic-gate fixed. I made a mistake, I created the DB but I created the table only later. The table had the wrong OWNER, changing it to "myuser" worked. Thanks for your support. It was my fault and I'd never have it fixed without your help.

**Comment by Logic-gate** [comment]
Cheers, Glad it worked.

**Comment by Attoy** [comment]
It works but my journal has a lot of
`error: error persisting value to postgres name=error, length=197, severity=ERROR, code=23505, detail=Key (key)=(about) already exists., hint=undefined, position=undefined, internalPosition=undefined, internalQuery=undefined, where=undefined, schema=public, table=entries, column=undefined, dataType=undefined, constraint=entries_key_key, file=nbtinsert.c, line=434, routine=_bt_check_unique`

I read the error code 23505 means `23505 | unique_violation` from https://www.postgresql.org/docs/10/static/errcodes-appendix.html

Is it another mistake of mine or is it something code related?

**Comment by Logic-gate** [comment]
Hey, 

Sorry, went offline for a bit.

Try this, remove the current table and initiate a new one with adequate permissions. 

It should work.

**Comment by Attoy** [comment]
Yes! You're the man! Thanks @Logic-gate :) I close the issue again, I hope this is definitive!
