### ISSUE TITLE
Raw page not triggering Firefox's JSONViewer

### ISSUE THREAD

**Issue by nihaals** [seejohnrun/haste-server#187]

**Comment by Logic-gate** [comment]
The raw view is served as a page, as in rendered as text not json. It is not supposed to trigger json view.

**Comment by OrangutanGaming** [comment]
Shouldn't there be a way to render it as JSON though? Even if you have to put the file extension on

**Comment by Logic-gate** [comment]
Hmmm, i am assuming that you want to programmatically get the "haste", if so and even if json is implemented, there would only one field, the paste. Regardless, @seejohnrun ping.

**Comment by MAGICCC** [comment]
I use the [JSONLite ](https://github.com/lauriro/json-lite) plugin for FireFox 58, and it triggers the render for me.
https://p.kthx.at/raw/tisosorije

But as @Logic-gate said, the page Content-Type itsself is text/plain

**Comment by seejohnrun** [comment]
Hit a URL like `https://p.kthx.at/documents/tisosorije` instead for JSON

**Comment by OrangutanGaming** [comment]
That's escaping it into a standard string, so it's pretty much useless

**Comment by seejohnrun** [comment]
@OrangutanGaming not sure what you mean by that - escaping the body? how else would it represent it if not as a string?

**Comment by Logic-gate** [comment]
So, you want something like this: 

```

{
   "haste":{
     "Code": "import test/nprint(test())"
     }
}


```

Again, if you are using it programmatically, accessing the document as text shouldn't be an issue.

**Comment by OrangutanGaming** [comment]
I'm not HTTP requesting it or anything, I just wanted it in that form so that it could trigger a JSON Viewer.

**Comment by seejohnrun** [comment]
https://p.kthx.at/documents/tisosorije does render in JSONView for me - but the body isn't going to render there since we can't assume that the body is also JSON.  You can decode it on the client side but otherwise I don't think haste-server will be a good fit

**Comment by OrangutanGaming** [comment]
I guess I'll try to find another site that already supports it

**Comment by OrangutanGaming** [comment]
Is it possible to have the type changed by a request header? So if I gave `Content-type: application/json`, would it be possible for it to change its response content type? That would solve it, as I can just make it so all requests to `hastebin.com/raw` will have that header added

**Comment by seejohnrun** [comment]
@OrangutanGaming you can do it easily enough by modifying https://github.com/seejohnrun/haste-server/blob/master/lib/document_handler.js#L39 locally

**Comment by OrangutanGaming** [comment]
I'm using `hastebin.com`, so I can't change it sadly
