### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amenolo** [seejohnrun/haste-server#188]
Disclaimer: this ain't an Issue...neither a Pull request I guess...just a silly question from a street guy :-)

It is by any chance possible to drop the "let-me-guess-the-syntax" suffix in the URL by default?
Thanks

**Comment by seejohnrun** [comment]
It is, but there's no setting for it - should be easy to remove by editing `application.js`.  What's the use case?

**Comment by amenolo** [comment]
It would be useful to me in order to get always the shortest URL, that's all :-)

Could you point out which section of application.js has to be editing? Thanks!

**Comment by seejohnrun** [comment]
Just comment out the line:

``` js
file += '.' + _this.lookupExtensionByType(ret.language);
```
