### ISSUE TITLE
Possibility to report a link

### ISSUE THREAD

**Issue by dlion** [seejohnrun/haste-server#196]
Usecase: I need/want to remove a pastebin, posted from someone else without my consent

Without a "Report" form or something similar I can't

**Comment by vwbusguy** [comment]
For what it's worth, we use redis as a backend, so I can just go into the redis and remove an entry.  Should be easy to remove in general, depending on your backend.

**Comment by webmastir** [comment]
That's exactly what we do, since our pastes are set to **not** expire.

**Comment by dlion** [comment]
Ok but what can I do if I found my personal informations exposed on https://hastebin.com/ ?
I have to contact the admin directly?
I think it's better to implement a way to `report` a paste to avoid any kind of problems
