### ISSUE TITLE
Complete cleanup of entire project

### ISSUE THREAD

**Issue by PassTheMayo** [seejohnrun/haste-server#198]
Hello, there. I was wondering, do you have any plans to completely rewrite the hastebin server in new ES6 classes and stuff? I am willing to do it for you guys, or help out. If you want me to, I can and I will do a pull request just say so. Thanks.

Note: I kinda actually want to rewrite hastebin, because I like ES6 and need a new project ;)

Note: I am going to anyways, and call it `haste-es6` :P

**Comment by seejohnrun** [comment]
I've started some of this work but wasn't in a huge rush to complete it.  Always willing to take contributions though!  I've been adding additional test coverage to files as I convert them

**Comment by PassTheMayo** [comment]
Ah, nice. Thanks for continuing the hard work on the project, it's a great service.
