### ISSUE TITLE
Unable to save or upload. 

### ISSUE THREAD

**Issue by Junnk** [seejohnrun/haste-server#199]
Hello, I'm unable to save or upload hastebins, I've tried the generic clearing cache, cookies, disabling plugins and more and nothing seems to be able to resolve this issue for me. http://jay-junnk.com/GVnHJ

**Comment by seejohnrun** [comment]
Is there an error in the server log?

**Comment by Junnk** [comment]
I'm very sorry but how do I see the server log? I'm unable to access any of the hastebin options. https://hastebin.com/about.md is a blank page for me.

**Comment by seejohnrun** [comment]
Oh sorry I didn't realize you were using hastebin.com - the above has been
fixed, thanks

**Comment by Junnk** [comment]
Thank you very much! It is now working. :)
