### ISSUE TITLE
Unable to save new pastes, existing ones won't load

### ISSUE THREAD

**Issue by Adubbz** [seejohnrun/haste-server#202]
Hey there, my apologies if this is the incorrect place to put this however it seems I am unable to save or load any pastes on https://hastebin.com/. 

After entering some text and pressing the save button, nothing happens for ~30 seconds, before a red box appears saying "Something went wrong!". Additionally, upon loading any page (https://hastebin.com/about.md for example) the page is blank, and a cursor appears after ~20-30 seconds. This behaviour happens on Chrome, Edge and Internet Explorer on Windows, as well as Safari on both macOS and iOS. I have also confirmed this with others as well. 

I hope the service is back to functioning normally again soon, since it's one that I, and I'm sure many others, enjoy using regularly. Thanks.

**Comment by seejohnrun** [comment]
This should be fixed now, thank you!

**Comment by TheMonDon** [comment]
I'm having this issue now

**Comment by Hundeklemmen** [comment]
same

**Comment by Gyzimo** [comment]
Jup i have the same problem.  it will not save it

**Comment by Dimentive** [comment]
I can’t save any Hastebeen pastes, no matter how long or short they are.

**Comment by Dimentive** [comment]
@seejohnrun It hasn’t been fixed; I’m having this issue right now. I can’t save any Hastebeen pastes, no matter how long or short they are.

**Comment by SylveonBottle** [comment]
Happening now.

**Comment by Gyzimo** [comment]
Yeah I thought I just closed brackets and killed all tasks in tasks mananger. Other then that is that not works then reinstalling is I think the only option.

**Comment by Kabouik** [comment]
Same here!

**Comment by weegeeweeg** [comment]
> This should be fixed now, thank you!

**Comment by beyzakorkmaz391** [comment]
It's not.

**Comment by 32** [comment]
Still happening.

**Comment by Dimentive** [comment]
Is this ever going to be fixed? I can’t save pastes at all, so Hastebin is useless.

**Comment by butcha** [comment]
Same issue here.

**Comment by Kabouik** [comment]
It works again for me, but I am not sure when it was fixed. I am using the Budgie "HasteIt" applet.

**Comment by butcha** [comment]
@Kabouik working here again now too 💪🤘

**Comment by jaylawl** [comment]
happening again

**Comment by butcha** [comment]
Yep, also happening here again now.

**Comment by SylveonBottle** [comment]
Please use an alternative hastebin domain.

https://haste.aetheryx.xyz/

**Comment by Kabouik** [comment]
Weird, I can confirm it still works for me with hastebin.com using the Budgie Haste applet.

**Comment by SylveonBottle** [comment]
Having this issue still.. jeez, every other day with this.
