### ISSUE TITLE
All pages empty

### ISSUE THREAD

**Issue by ghost** [seejohnrun/haste-server#206]
Hi seejohnrun,

I opened a paste and it was empty, while it was shared about 12 hours ago. Weird. I decided to click on the Hastebin about page, hastebin.com/about.md, only to find out that this one's empty too.

On my iPhone Safari it doesn't work either. Edge/Firefox/Chrome all don't work. I even tried enabling a VPN. What is my issue here? Do I have to install something in order to see public pastes?

**Comment by ItsCEED** [comment]
They have issue or something.

**Comment by loliprotector** [comment]
#242 Still happens even now, but intermittently.

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
