### ISSUE TITLE
Add Docker + Kubernetes Support

### ISSUE THREAD

**Issue by cmattoon** [seejohnrun/haste-server#211]
I've used haste-server in the past as a standalone app, and recently containerized and deployed it to a Kubernetes cluster. Since there are several existing PR's for Docker support, I figured I'd add yet another image, plus the Helm Chart to install. It's not quite production-ready, but the gist is that a user can install the app to k8s with a command like:

    helm install --set backend.type=file haste-server

Other Docker PRs:

 - #57 is using `ubuntu:12.04`
 - #121 is using `centos:6`
 - #124 is using `alpine:3.6`
 - #171 is using `node:slim`

The Chart doesn't make provisions for different storage backends or other things yet, but should work with `helm install ./helm-server` from inside the project root. You'll need a running k8s cluster (or minikube) and Helm to test this. Another option would be `docker-compose`, which could bring up haste-server and a given backend with one command. 

I'm attaching a PR with the rough draft, and happy to make adjustments

**Comment by vwbusguy** [comment]
I use a simple Dockerfile:

```
FROM node:slim

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN npm install
CMD ./start-haste.sh
EXPOSE 7777
```

**Comment by seejohnrun** [comment]
Thank you I've recently merged a basic `Dockerfile`
