### ISSUE TITLE
Not loading stylesheets and js

### ISSUE THREAD

**Issue by jamesxsc** [seejohnrun/haste-server#220]
I am using IIS on server 2012 R2 and if you to https://paste.615283.net/server.js then you'll see whats wrong, sometimes i can load to https://paste.615283.net/static/index.html but when trying to save i get an error. Any ideas why?

**Comment by 615283** [comment]
note: i am using iisnode

**Comment by seejohnrun** [comment]
Hi I've never used IIS (maybe once a super long time ago) so I don't have much to help you unfortunately.  Maybe someone else can provide more detail if you give some more error logs or something?

**Comment by Wohlstand** [comment]
HasteServer is web-server by itself, and I think you better to try to use regular Node.JS for Windows separately, and only use ISS to forward the requests to that host. For example, to `127.0.0.1:5000`. Instead of `5000` put the port you have set in your config.

**Comment by 615283** [comment]
Not sure where I'd find them, but next thing I'll try is permission based issues.

**Comment by 615283** [comment]
Also @seejohnrun what is the page that it should first load to? `server.js` or `static/index.html`?

**Comment by seejohnrun** [comment]
`static/index.html` loads `server.js`

**Comment by 615283** [comment]
Now using node js with `npm start`. But am encountering another issue, firstly, how can I host it on a port like 7777 and then just have a domain pointing to it (I am using cloudflare), when trying to access with my domain and suffixing the port, I get that the connection has been unexpectedly closed by the host.

**Comment by kib** [comment]
https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with- clearly states those ports are not reverse proxied. Don't run on those ports if you want to use cloudflare. It is easy enough to something like haproxy or nginx in reverse proxy mode in front of it so it is available ofn port 80. I have no idea why you would want to run IIS in front, or why you would want to run it on port 7777.

**Comment by 615283** [comment]
Would these proxy softwares work with IIS installed on the same machine hosting other sites?
