### ISSUE TITLE
Hastebin.com down again? 

### ISSUE THREAD

**Issue by Rayzr522** [seejohnrun/haste-server#222]
Is hastebin.com down again? All attempts to create a new haste are returning a 503 Service Unavailable error.

**Comment by Rayzr522** [comment]
It no longer appears to be down, but I'm curious as to why it stopped functioning all of a sudden. One of my pieces of software uses hastebin.com for uploading large bits of text, so if this is prone to happen again, I would appreciate a heads up so I can move to a different text upload service. Thanks in advance :)

**Comment by seejohnrun** [comment]
@Rayzr522 I try my hardest to avoid any downtime, but I'm supporting this and paying the bills for it out of my own pocket and have been doing so for quite a while.  If you need something with a higher degree of uptime, I'd recommend maybe switching as I definitely can't make any guarantees at this time.  There's also always the option of hosting your own `haste-server` if you're interested.
