### ISSUE TITLE
*.cs C# highlighting doesn't seem to be working for me

### ISSUE THREAD

**Issue by MostHated** [seejohnrun/haste-server#225]
Here is an example. https://hastebin.com/otuqirinux.cs

It detected the code as swift for some reason and that seems to be the only one that wants to do any highlighting. using .cs doesn't seem to be working, unless it is just something on my end, though I tried multiple browsers. 

Thanks,
-MH

**Comment by seejohnrun** [comment]
:wave: @MostHated - the highlighting here actually runs through highlight.js

It could be that this has been fixed in a more recent version. Are you able to check detection with: https://highlightjs.org/ ?
