### ISSUE TITLE
Line numbers won't align with code (custom font)

### ISSUE THREAD

**Issue by Qwerty-Space** [seejohnrun/haste-server#226]
I'm using Source Code Pro font on my hastebin server, but after a while the line number misalign.

![image](https://user-images.githubusercontent.com/6967592/41204937-208f7708-6ce3-11e8-86c7-2d42e742aab7.png)

**Comment by seejohnrun** [comment]
Odd / any chance the font heights are slightly different?

I'm going to close this for now but please re-open if there's something actionable or you have more issues
