### ISSUE TITLE
How to connect to a domain?

### ISSUE THREAD

**Issue by bionichuman** [seejohnrun/haste-server#234]
How do I connect this to a domain? I have a vps. It is working on local host.

**Comment by bionichuman** [comment]
what port should it be set to in the config? 
@MAGICCC

**Comment by MAGICCC** [comment]
The one you want to use...

**Comment by bionichuman** [comment]
@MAGICCC How would I install ghost bin on domain.com/ghost

I dont want it on front page...

**Comment by webmastir** [comment]
@bionichuman if you're going to open this up to the public, you should consider using a reverse proxy. 

https://stackoverflow.com/questions/16770673/using-node-js-only-vs-using-node-js-with-apache-nginx

**Comment by bionichuman** [comment]
You guys know of files or how to host ghost bin? It has a few more features than this...

Also How would I install ghost bin on domain.com/ghost

I dont want it on front page...

**Comment by MAGICCC** [comment]
Since this isn't a valid Hastebin issue, you may close this!
Also I suggest reading into hosting a webserver and not doing something where you have zero knowledge! I don't like people who don't know what they are doing and therefore risking that their servers will be compromised and thirdparty users will damage other people.

**Comment by bionichuman** [comment]
@MAGICCC I understand webhosting but would like to know how to put this on domain.com/hastebin


Can you please help me do that.

**Comment by MAGICCC** [comment]
No, @webmastir suggested that you may use a reverse proxy for this

**Comment by bionichuman** [comment]
@MAGICCC Do you know how to make an account login and encryption for pastes for this?

**Comment by MAGICCC** [comment]
This project doesn't have such functionalities. You should either build your own login page or use pre-done ones...

**Comment by bionichuman** [comment]
@MAGICCC Do you know if the creator will ever publish the code that is currently running right now? He hasnt responded to my email or tweets....

**Comment by MAGICCC** [comment]
The current master branch is the code which is running at the moment

**Comment by bionichuman** [comment]
@MAGICCC Oh, thank you. It hasnt been updated in awhile that is why I was wondering.

**Comment by MAGICCC** [comment]
The last commit was 6 days ago...
https://github.com/seejohnrun/haste-server/commits/master

**Comment by mjmalec** [comment]
This is for Hastebin, not Ghostbin. Maybe try sticking to the appropriate repositories next time?
