### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by mattmalec** [seejohnrun/haste-server#235]
Got Haste installed. But saving pastes, it
gives me a “Something went wrong” error. Checked my browser console, seems like /documents/static is empty. At one point I changed that URL so it would be the static folder like /static. Regardless of changing that, nothing has done the trick. Using Memcached for my document storage type. Not sure if that’s the problem.

Appreciate the help in advance.
-Matt

**Comment by seejohnrun** [comment]
Are there any errors in the server log?

**Comment by mjmalec** [comment]
No errors in the server logs.

**Comment by seejohnrun** [comment]
I realize it's been a long time since this issue was opened, and apologize for not reaching out sooner

If anyone comes upon this later, please check that you can connect to memcached directly and that it's working as expected.

As always, feel free to re-open this issue if this is still relevant
