### ISSUE TITLE
Invalid transport, must be an object with a log method.

### ISSUE THREAD

**Issue by bgbrandongomez** [seejohnrun/haste-server#236]
I am trying to install hastebin onto a Raspberry Pi 3 running headless (lite) Raspian. I installed npm using [this guide](https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-Install-Node.js-via-Package-Manager-*(Recommended)*). Also, I used `npm audit fix` and then `npm audit fix --force` prior to installing hastebin using [this README](https://github.com/seejohnrun/haste-server/blob/master/README.md).

I tried starting the server and ran into [this bug](https://hastebin.com/ukohuvaxul.coffeescript) and decided that I may need to setup a database, so I installed redis-server via apt and then redis via npm. The error is still the same. Here is the [log](https://hastebin.com/izodovadol.rb) mentioned by the error that was thrown.

The error is `Invalid transport, must be an object with a log method.`

**Comment by ludovicoloreti** [comment]
any news?

**Comment by bgbrandongomez** [comment]
No, I decided to go with [Modern Paste](https://github.com/LINKIWI/modern-paste) instead.

**Comment by chrisderwahre** [comment]
I had this issue aswell, i edited `package.json`  changed `winston` to `2.*` under dependencies
