### ISSUE TITLE
Are you also running hastebin.com?

### ISSUE THREAD

**Issue by spookyahell** [seejohnrun/haste-server#238]
Because if you are you should know the site isn't operating at all (not the about page, no new posts loading & also no existing posts loading)

**Comment by lieuwe-berg** [comment]
I'm having the same issue, keep getting `Error: 503 Service Unavailable` when POSTing to hastebin.com/documents.

**Comment by loliprotector** [comment]
#242 Same issue here at random times.

**Comment by seejohnrun** [comment]
Please see https://github.com/seejohnrun/haste-server/pull/251 and thanks for the report
