### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by OfficerX** [seejohnrun/haste-server#243]
Hello,
sometimes I cant see or post any pastes including the about page.
http://prntscr.com/koiqxa
Ive also tried different browsers such as chrome and firefox.

**Comment by loliprotector** [comment]
#242 Seems to be an issue to a lot of people.

**Comment by seejohnrun** [comment]
Please see https://github.com/seejohnrun/haste-server/pull/251 and thanks for the report
