### ISSUE TITLE
Invalid syntax checking

### ISSUE THREAD

**Issue by tbhaxor** [seejohnrun/haste-server#244]
I wrote a code
```python
import math

print(math.factorial(6))
```

which is `.py` i.e python script, but your service is reading it as `coffescript`

**Comment by seejohnrun** [comment]
:wave: highlighting and detection are handled by the https://highlightjs.org/ library, maybe worth opening up an issue over there but typically with short code snippets detection is pretty difficult because there isn't a lot of signal to base the decision on. Thanks!
