### ISSUE TITLE
Pastes won't save

### ISSUE THREAD

**Issue by Benlewis9000** [seejohnrun/haste-server#245]
Website loads and allows me to paste my code, however when I try to save it is completely unresponsive. Sometimes it gives a red error message "Something went wrong!". Not much more to say.

**Comment by bionichuman** [comment]
@Benlewis9000 I may be able to hep you. Contact me on discord. 
BionicHuman
#3200

**Comment by loliprotector** [comment]
#242 Still intermittent issues, sometimes it works, sometimes it's just this.
about.md is empty as well so I'm not sure what's happening to the server.

**Comment by Aericio** [comment]
I also have this problem. I am not able to save any files / view any other files.

**Comment by RUSshy** [comment]
This is because their server is written in ruby, inreliable software

**Comment by bionichuman** [comment]
Host your own server then it works... Easy to setup.

**Comment by regalstreak** [comment]
Same on hastebin.com.
Can anyone link me a hastebin alternative server?

**Comment by Aericio** [comment]
It seems to be back now... hope it stays like that :x

**Comment by seejohnrun** [comment]
Please see https://github.com/seejohnrun/haste-server/pull/251 and thank you for the report
