### ISSUE TITLE
Hastebin.py post request returns nothing.

### ISSUE THREAD

**Issue by DanielDublin** [seejohnrun/haste-server#246]
Hey there, i'v been using hastebin for my bot for the past few months, but once every month in the last 2 months, the API just bugs out and fixes itself later on...
Every time I use the code below I get 

>expecting value line 1 column 1 (char `0`) 

And if that isn't enough it kinda terminates the connection with discord PY.
I usually post a list of names, like a grocery list... should be that long nor complex tbh...
Is this a problem with the hastebin.py or did I miss something?

    async def post(content):
        try:
            post =  requests.post("https://hastebin.com/documents", data=content.encode('utf-8'))
            return  "https://hastebin.com/" + post.json()["key"]
        except Exception as e:
            print ("CRASHED IN EXCEPTION when sending hastebin link - ",str(e))
        return "Failed to send link"

**Comment by SkiddieTech** [comment]
POST API seems to be down for me aswell?

**Comment by Hazmi35** [comment]
#242

**Comment by Hazmi35** [comment]
#242

**Comment by seejohnrun** [comment]
Thank you for the report, please see https://github.com/seejohnrun/haste-server/pull/251
