### ISSUE TITLE
Hastebins down again

### ISSUE THREAD

**Issue by ubscal** [seejohnrun/haste-server#248]
title says it all

**Comment by ALPHA-sh** [comment]
yep it is

**Comment by didinele** [comment]
Heya, @ubscal I am someone that often uploads code to hastebin and I was really triggered about this as well until I found out about this site: https://hasteb.in/

**Comment by seejohnrun** [comment]
I realize this has been pretty frustrating (for me as well), and I believe it should be resolved by https://github.com/seejohnrun/haste-server/pull/251 please report again if you see this issue I'd like to resolve this once and for all :)
