### ISSUE TITLE
Not able to save a new file

### ISSUE THREAD

**Issue by Jaden-Lee** [seejohnrun/haste-server#249]
> Hey there, my apologies if this is the incorrect place to put this however it seems I am unable to save or load any pastes on https://hastebin.com/.

> After entering some text and pressing the save button, nothing happens for ~30 seconds, before a red box appears saying "Something went wrong!". Additionally, upon loading any page (https://hastebin.com/about.md for example) the page is blank, and a cursor appears after ~20-30 seconds. This behaviour happens on Chrome, Edge and Internet Explorer on Windows, as well as Safari on both macOS and iOS. I have also confirmed this with others as well.

> I hope the service is back to functioning normally again soon, since it's one that I, and I'm sure many others, enjoy using regularly. Thanks.

This Issue was #202, but it is happening again. I also would like this service to be fixed. While trying to save my file, after 20-30 seconds, a red box appears saying "Something went wrong!"

**Comment by seejohnrun** [comment]
please see https://github.com/seejohnrun/haste-server/pull/251 and thank you for the detailed report
