### ISSUE TITLE
staticMaxAge: Documentation request.

### ISSUE THREAD

**Issue by chamunks** [seejohnrun/haste-server#250]
A lot of the configuration doesn't seem to have as much clarification.  
`staticMaxAge - max age for static assets (86400)` this is just an arbitrary number to me.  Is it minutes?  Seconds?  Milliseconds?  I mean I imagine 86400 means 60 days which defies documentation that states 30 minutes.

If its milliseconds it's definitely not very long and if its seconds that means the pastes by default expire in 24 hours...

There are other time-based things like the rate limit, how fast is the rate limit?  Because I have no idea and digging around in the repository it doesn't seem any clearer afterwards.

**Comment by chamunks** [comment]
After reading the packages that are imported into this project say that it's milliseconds but seems weird that the default would be a minute and 26 seconds.

**Comment by seejohnrun** [comment]
@chamunks the max age for the cache control header should be in seconds. `86400` is 1 day (`86400 / 60 / 60`).

I don't believe anywhere in the documentation it states 30 minutes. That sounds similar to the number in the config mentioned in the `about.md` on https://hastebin.com which is a different number than this one:

* `staticMaxAge` is the cache control value for static assets (ie: `about.md`) for browser caching (see https://www.keycdn.com/blog/http-cache-headers/)
* `expires` is the amount of time before a given key should expire automatically

I'm happy to make a change to the README for more clarity but will wait on your response before doing so!

**Comment by chamunks** [comment]
Oh also the ratelimit time whats that in?  I imagine 5 minutes at this point but that'd be excellent information to get clarification on.

**Comment by seejohnrun** [comment]
Thanks @chamunks !
