### ISSUE TITLE
I can't save

### ISSUE THREAD

**Issue by Ondra3211** [seejohnrun/haste-server#252]
Hello, I can't save my pastest and I see nothing in about.md

My page: https://haste.zerocz.eu

Log 1
https://pastebin.com/icJZzhgJ
`
Log 2
https://pastebin.com/3mkdyLvh

**Comment by seejohnrun** [comment]
It seems like the server is having trouble writing into memcached - can you confirm that it is up and running and you can save into it?

**Comment by Ondra3211** [comment]
How?

**Comment by seejohnrun** [comment]
`telnet localhost 11211` should do it and then issue a memcached command and check the response

**Comment by Ondra3211** [comment]
`root@ns31622:~# telnet localhost 11211
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
`

**Comment by seejohnrun** [comment]
yep it looks like your memcached instance needs some additional configuration. I don't know much about it, but I'd try googling around. that command will need to work before using hastebin with memcached

**Comment by Ondra3211** [comment]
I fix it. I use this command `apt-get install memcached`. `npm install memcached` not working

**Comment by seejohnrun** [comment]
Sounds good and makes sense

`apt-get install memcached` would install the memcached server and `npm install memcached` would either not work or if the package exists likely install an npm memcache client library

Thanks!
