### ISSUE TITLE
'npm start' yields "23 error Failed at the haste@0.1.0 start script 'node server.js'."

### ISSUE THREAD

**Issue by SparklingComet** [seejohnrun/haste-server#256]
If this is a duplicate issue, I am sorry.

I ran `npm install` both with and without the `-g` flag and it seemed to work fine. When I executed `npm start`, it wouldn't.

`npm-debug.log` file: https://hastebin.com/owiniragoh.rb
`config.js`: https://hastebin.com/nulokereru.json

I am opening the issue as instructed by log output. Any chance you can tell me what I am doing wrong?

**Comment by seejohnrun** [comment]
I know it's been a bit, and doubt this is still an issue but if there's any way I can help please reach out and feel free to re-open this
