### ISSUE TITLE
Cannot save pastes; it's happening again

### ISSUE THREAD

**Issue by travddm** [seejohnrun/haste-server#257]
Supposedly fixed by #251, the issue described in #202 is happening once again. When I try to post a paste, the request hangs for 30 seconds and returns a 503 error.

**Comment by neuman1812** [comment]
Just want to add I tried saving a new paste today.  Unable to save.  The save button wont respond at all.  Tried both firefox and chrome with cache cleared and all ad blockers turned off.

**Comment by TeamDman** [comment]
Currently having the issue as well, no extensions or adblockers loaded.

**Comment by Hundeklemmen** [comment]
same

**Comment by Gangster8192** [comment]
```
Cannot Save Either
```

**Comment by MyriaCore** [comment]
Yep, happening with me too at the moment. Sorta crazy that this seems to have been going on for 4 months straight.

**Comment by Dimentive** [comment]
I’m having exactly the same issue: I can’t save any Hastebeen pastes, no matter how long or short they are.

**Comment by skylerspark** [comment]
HAPPENING TO ME TOO UGHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by aaditisawesome** [comment]
Same! It just worked last night...

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
