### ISSUE TITLE
Hastebin is down... again...

### ISSUE THREAD

**Issue by ubscal** [seejohnrun/haste-server#259]
Hastebin is application error again

**Comment by didyouexpectthat** [comment]
Seems up for me.
![image](https://user-images.githubusercontent.com/1329077/46911477-d8977b80-cf11-11e8-9160-3506b6c27128.png)

**Comment by TheTeaCup** [comment]
i can pull up the site but i can't send anything

**Comment by etiennepinchon** [comment]
Up! Same here! :'( Application error

**Comment by MisterFixx** [comment]
Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

**Comment by etiennepinchon** [comment]
What about the data stored on hastebin? Any way to get something back?

**Comment by MisterFixx** [comment]
Unfortunately not until it starts working again

**Comment by didyouexpectthat** [comment]
Hastebin has been up since at least end of last week.
![image](https://user-images.githubusercontent.com/1329077/60466260-063f6480-9c08-11e9-8258-67343ff73bf3.png)

**Comment by GitauHarrison** [comment]
> Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

Thank you. Saves the day

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state

**Comment by EricoCartmanez** [comment]
> Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

I wonder how nobody noticed this one. It works great, thank you.

**https://pastie.io**
