### ISSUE TITLE
Not able to access old ones or create new for about couple of hours

### ISSUE THREAD

**Issue by mvsuryatejactb** [seejohnrun/haste-server#261]
Checked the browser network panel, while creating new doc. Observer the response code is 503 while creating new.

> Request URL: https://hastebin.com/documents
> Request Method: POST
> Status Code: 503 

Same case while fetching existing doc too.

> Request URL: https://hastebin.com/documents/about
> Request Method: GET
> Status Code: 503

**Comment by mvsuryatejactb** [comment]
Hi @seejohnrun , any updates on this?

**Comment by mvsuryatejactb** [comment]
Wow! More than 6 hours and nobody to give a damn..

**Comment by seejohnrun** [comment]
@mvsuryatejactb Thanks for the report. I've been running and paying for this site for a very long time completely by myself as a service to the community (with no ads mind you, look at other pastebin softwares for comparison). I'm sorry the service went down, but messages like this feel pretty toxic.

I definitely care or I wouldn't be running this site at all and continuing to pour money in every month to keep it running for people I don't know.

I'll keep doing my best working to keep downtimes like this from happening, and if a 6-hour turnaround in the middle of the night (ET, while I'm sleeping) is this unacceptable you may want to choose another service to fit your needs (or run it yourself, the software is open source as well).
