### ISSUE TITLE
Cant save pastes again

### ISSUE THREAD

**Issue by ubscal** [seejohnrun/haste-server#264]
title says it all

**Comment by fiservedpi** [comment]
agreed

**Comment by Benjozork** [comment]
seriously, this happens every two days lmao. I think im gonna host my own instance

**Comment by fiservedpi** [comment]
Can you make it dark themed?

**Comment by Benjozork** [comment]
isn't hastebin.com already dark themed ?

**Comment by fiservedpi** [comment]
Yeah but still doesn't save been a week

**Comment by Benjozork** [comment]
it worked for a short moment today actually lmao

probably some sort of ratelimit.

but yeah if I had enough money for hosting I would do it

**Comment by MostHated** [comment]
It's a shame that this happens so often, I love hastebin.com, it is always my go-to whenever I need to quickly share something with a pal or whathaveyou.  I wish I could try and help out, but I had to cancel my own server for the time being as I am between contracts at the moment.

**Comment by Benjozork** [comment]
I can make it but I won't host it myself, that's what I'm saying

**Comment by bionichuman** [comment]
I have a way to host it for free and it works great. Contact me via discord BionicHuman
#3200

or just send a message on here. 


I will show you how to host it for free but would like a donation from anyone who I show as I took 3+ months working on it.

**Comment by Benjozork** [comment]
It works again :)

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
