### ISSUE TITLE
Hastebin.com savebutton not working 

### ISSUE THREAD

**Issue by fiservedpi** [seejohnrun/haste-server#265]
it seems the website is unable to to save getting red text with error

**Comment by Arthurooooo** [comment]
same here, and I can't see any paste

**Comment by ubscal** [comment]
same bro

**Comment by sinker1345** [comment]
yup same here

**Comment by CalledHadi** [comment]
Same cant see anything

**Comment by AllianceSky-PS** [comment]
Same thing happening since last 1 hour.

**Comment by MyriaCore** [comment]
This issue seems to be related to #257

**Comment by penright** [comment]
Happen to me yesterday morning, then tested last night and it worked. Needed it this morning and it is doing it again. Just to be clear, when trying to save a red box with "something went wrong" message

**Comment by TheCardinalSystem** [comment]
Same deal.

**Comment by fiservedpi** [comment]
Guess this project is anointed abandoned
