### ISSUE TITLE
JSON highlighting incorrect w/ extension in URL.

### ISSUE THREAD

**Issue by Brend4n** [seejohnrun/haste-server#267]
Steps to reproduce:
- Paste JSON
- Refresh page w/ json link in url (Highlighting will be incorrect)
- Removing extension from URL will fix the highlighting issue.

![](https://i.noodle.pw/aA81F.gif)

**Comment by Laiteux** [comment]
This is still relevant and annoying.

**Comment by Laiteux** [comment]
**Temporary fix**
Comment theses lines: https://github.com/seejohnrun/haste-server/blob/master/static/application.js#L249-L251
