### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by damiannes** [seejohnrun/haste-server#269]
http://prntscr.com/lgs86o
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by willshiao** [comment]
I get the same error when visiting the site today. I am unable to access existing pastes or create new ones. I also tried visiting the site about 3 days ago and received the same error, so it seems more than a one-time occurrence.

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
