### ISSUE TITLE
i think hastebin down

### ISSUE THREAD

**Issue by Scrub911** [seejohnrun/haste-server#270]
I can't upload my shit it just gives me an error.
and https://hastebin.com/about.md won't load

I have tried it on chrome firefox and even edge

**Comment by Wohlstand** [comment]
It also works from here (Russia, Firefox 63.0.0 on Linux Mint 19) same pretty normal.

**Comment by Scrub911** [comment]
it didn't work when i posted this but now it does, probably just a server issue they fixed
