### ISSUE TITLE
Hastebin doesn't save and load, I need for homework

### ISSUE THREAD

**Issue by feneryig** [seejohnrun/haste-server#276]
Hastebin doesn't load, even doesn't save. Things I tried ->
- Google Chrome with ADP (location Turkey)
- Google Chrome with ADP (Hotspot Shield Chrome Ext)
- Mobile Google Chrome (Turkey Vodafone)
Can you help? I need at least it for Monday.

**Comment by feneryig** [comment]
(hastebin.com)

**Comment by bigbn** [comment]
![image](https://user-images.githubusercontent.com/740864/52106626-f3027b80-260c-11e9-9024-7fdf4329b768.png)

**Comment by FernanDK** [comment]
well that's no good

**Comment by MostHated** [comment]
As much as I absolutely love hastebin, I would personally try to avoid depending on it for anything as important as homework or anything professional. There have been quite a few times when I wanted to show something quick to a colleague or boss and it wasn't working and I was like "shit!"

**Comment by ir-3** [comment]
It doesn't work more than it does work. I have been trying to use it's API in a small project to show stuff and it just can't be depended on.

**Comment by MostHated** [comment]
It's a shame, too as it is easily the best thing out there for sharing code.

**Comment by ir-3** [comment]
I am currently using my friends own version for more reliable hosting.

**Comment by TheCloudSaver** [comment]
Yup, having the same issue sadly.

**Comment by archiebaer** [comment]
It seems to be back up. I would never really rely on a demo website though. Self-host it.

**Comment by kensoh** [comment]
Getting the same issue now, unable to save text

**Comment by kensoh** [comment]
Works now!

**Comment by Dimentive** [comment]
Still doesn’t work.

**Comment by archiebaer** [comment]
As I said before, this is a demo website, so you shouldn't rely on it. Self-host it, that's the point of hastebin.

**Comment by Dimentive** [comment]
I still expect it to work. I don’t understand why it doesn’t do anything. And what do you mean it’s a demo website?

**Comment by archiebaer** [comment]
It is showing you what Hastebin can do. The idea is you download it and host it on your own server. That's why it exists - So people can have a self-hosted alternatives to Pastebin or Gists.

**Comment by Dimentive** [comment]
Hastebin can't do anything, apparently.

**Comment by archiebaer** [comment]
If you're going to be rude, then why are you on it's repository? I find it very useful, it's nobody else's fault if it doesn't work exactly how you want.

**Comment by BarbzYHOOL** [comment]
it can't save either but it worked long ago

**Comment by Jeadness** [comment]
still no work

**Comment by zneix** [comment]
This project has been abandoned by the owner. However you can use [my fork](https://github.com/zneix/haste-server) instead. My instance available to public can be found [here](https://haste.zneix.eu).

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
