### ISSUE TITLE
Selfhosted: Not working at all

### ISSUE THREAD

**Issue by ohnoitsraining** [seejohnrun/haste-server#290]
The screen loads but I can't type, create a new paste, or save them. Nothing is happening. Any help would be appreciated.

**Comment by DJ-BB** [comment]
Did you fix this? I have same problem too. I didn't change anything other than the storage from memcached to file either lol. Guess it's just broken

**Comment by bionichuman** [comment]
I was able to get it working in glitch.com

**Comment by DJ-BB** [comment]
Really! How? I'm looking at your files and it looks like we both did the same things

**Comment by bionichuman** [comment]
How and what files of mine are you looking at?

Send me what you are looking at of mine and I can explain.

**Comment by DJ-BB** [comment]
Is this not you? https://glitch.com/edit/#!/hastebin?path=config.js:9:0
Sorry I haven't used glitch before so I don't know how it works.

**Comment by DJ-BB** [comment]
Literally the only thing I changed when after I downloaded haste-server was change the config file so that the host wast pointing at my web vm and I changed the storage to this 
```
"storage": {
  "path": "./.env",
  "type": "file"
  },
```

**Comment by ohnoitsraining** [comment]
I'm still using localhost and I only changed the storage to file storage. And it's not working for me. 

@bionichuman can you walk me through, step by step, on what you did to get it running.

**Comment by seejohnrun** [comment]
@ohnoitsraining are there any errors you can paste?

Going to close this issue for now but please re-open if this is still relevant and you'd like help
