### ISSUE TITLE
Allow the author of a file to edit

### ISSUE THREAD

**Issue by wolfy01** [seejohnrun/haste-server#294]
It would be nice if you could edit a file instead of making a whole new one.

**Comment by D347HxD** [comment]
With this, having the option for logins and being able to set it so only people with accounts can make pastes would go a long way to make this the best self hosted paste bin

**Comment by rybot666** [comment]
The issue with this is that this needs accounts, which is what hastebin isn't. Having to log in adds time and effort to a service designed for quick sharing. If you did it by IP, people would spoof and could edit any post using the API

**Comment by D347HxD** [comment]
If it's done like pastebin logins, you can allow the system administraor to 
Enable / disable account registration
Enable / disable guest paste creation

And allow the person creating the paste to select if the paste they are sharing is viewable to the general public (via the link key) or would need to be a registered user to view.
By default, set it so all pastes shared are shared publicly (so any user who doesn't have an account can still read said shared paste, but just cant create their own if the system admin turned that off)

**Comment by seejohnrun** [comment]
Agree with the comments above by @rybot666 and I'm not going to be adding editing to hastebin.com for now. I appreciate your time and this issue
