### ISSUE TITLE
522: Connection timed out

### ISSUE THREAD

**Issue by Unihedro** [seejohnrun/haste-server#295]
as shown below the site appears to be down.

![image](https://user-images.githubusercontent.com/5595067/60844281-6c7d4600-a20b-11e9-90f2-1064b921479d.png)

**Comment by Pxrple** [comment]
This wouldn't be the place for that.

**Comment by MisterFixx** [comment]
Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

**Comment by seejohnrun** [comment]
Working on fixes to this now / I continue to pay for these servers every month but need to increase the provisioning as the traffic has grown and I just haven't kept up with it. Thank you for the issue and your time
