### ISSUE TITLE
Connection Time out at night

### ISSUE THREAD

**Issue by Canine8YT** [seejohnrun/haste-server#297]
yea so at night i get this error 
![image](https://user-images.githubusercontent.com/50190590/60860613-f661ea80-a1dc-11e9-8097-da15d366fd12.png)

**Comment by MisterFixx** [comment]
For me it's been like this for at least a week now.
Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

**Comment by seejohnrun** [comment]
Working on this now as it's gotten much worse lately.
I pay for this project from my own pocket and it's been tough keeping up with traffic but will get things fixed
