### ISSUE TITLE
fresh install 'something went wrong' when save

### ISSUE THREAD

**Issue by robertparkerx** [seejohnrun/haste-server#298]
I'm on a fresh install and the server is up and rrunning but when I try to 'save' anything paste it comes up with a message 'something went wrong'. logfile.log doesn't report anything.

**Comment by mozartrafi** [comment]
Yeah, me too, i can't save and get the link of them.

**Comment by MaximeGir** [comment]
+1!

**Comment by ionstorm66** [comment]
Make sure memached is installed and running on the local machine first.

**Comment by BenJule** [comment]
or redis

**Comment by robertparkerx** [comment]
I am using file storage. I've tried using memcached but experience the same. I have redis running on another app so I can't use that. I've tried installing on another machine and experience the same problem.

**Comment by seejohnrun** [comment]
Is there any relevant information in the application logs?

Going to close this issue since it's been a bit plus please re-open if this is still an issue you'd like help with
