### ISSUE TITLE
hastebin.com still down??? can't even access any of the notes/info now, and they're stored on hastebin.com - how could something be down for this long??

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [seejohnrun/haste-server#301]
hastebin.com still down??? 

- can't even access any of the notes/info now, and they're stored on hastebin.com 
- how could something be down for this long??

**Comment by Wohlstand** [comment]
I have checked that, it works... Anyway I think the cache of them has gone.

**Comment by MisterFixx** [comment]
Why do you even store important notes on hastebin in the first place? even if hastebin wasn't down they would be deleted in 31 days

**Comment by Wohlstand** [comment]
So, for important notes, you should install haste-server on your own server/VPS, and set it up to keep notes forever. `hastebin.com` is made for quick sharing of some text things and intended to be temporary.

**Comment by SolveAllProblemsRightNow** [comment]
1. so it works right after i made this issue? but how could it have been down for 15 days or so? 

2. how could this site have constant problems over time for so long? what host is this site using??

**Comment by SolveAllProblemsRightNow** [comment]
3. why do you think the cache for them is gone? it's not gone

4. info does not expire in '31 days' - see/check the readme

**Comment by MisterFixx** [comment]
5. i think we understand that you can count, you can stop now.
No one owes you shit, this is a public open source repository, if you're not satisfied with the up time, go fork it and run it yourself you fucking lazy ass.

**Comment by SolveAllProblemsRightNow** [comment]
doesn''t even answer the question, wtf

**Comment by FerLuisxd** [comment]
> He doesn't owe you shit you stupid fuck, in the time you waited for him to answer you could have learned node.js and how to set up your own instance of hastebin, just shut the fuck up

Why are you being toxic? Says a lot about you

**Comment by MisterFixx** [comment]
> Why are you being toxic? Says a lot about you

agreed, i deleted it

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
