### ISSUE TITLE
{"message":"Document not found."} on hard reload

### ISSUE THREAD

**Issue by ManuDeBuck** [seejohnrun/haste-server#304]
When doing a hard reload `^+SHIFT+R` the server redirects to `/raw/undefined` and gives the message {"message":"Document not found."}. I do think this is unwanted behavior.

**Comment by seejohnrun** [comment]
If this is still an issue you're having and not too much time has passed please re-open. There's not enough detail here to know if this is running locally or on hastebin.com but that info would be helpful

**Comment by abhiram555** [comment]
> hastebin.com

same issue on hastebin.com
