### ISSUE TITLE
 Unexpected token : in conf file

### ISSUE THREAD

**Issue by tekmans** [seejohnrun/haste-server#305]
My haste-server was working for a really long time.. and it had been restart and failed with

`# /usr/bin/node /var/www/haste-server/config.js`

`/var/www/haste-server/config.js:3`
`  "host": "0.0.0.0",`
`        ^`
`SyntaxError: Unexpected token :`
`    at Module._compile (module.js:439:25)`
`    at Object.Module._extensions..js (module.js:474:10)`
`    at Module.load (module.js:356:32)`
`    at Function.Module._load (module.js:312:12)`
`    at Function.Module.runMain (module.js:497:10)`
`    at startup (node.js:119:16)`
`    at node.js:906:3`

Nothing had been changed or updated on this server (debian 8)
The localhost access is allowed

Any suggestion ?

the conf
`{`
`  "host": "0.0.0.0",`
`  "port": 7777,`
`  "keyLength": 10,`
`  "maxLength": 4000000,`
`  "staticMaxAge": 525600,`
`  "recompressStaticAssets": true,`
`  "logging": [`
`    {`
`      "level": "verbose",`
`      "type": "Console",`
`      "colorize": true`
`    }`
`  ],`
`  "keyGenerator": {`
`    "type": "phonetic"`
`  },`
`  "rateLimits": {`
`    "categories": {`
`      "normal": {`
`        "totalRequests": 500,`
`        "every": 60000`
`      }`
`    }`
`  },`
`  "storage": {`
`  "path": "./data",`
`  "type": "file"`
`  },`
`  "documents": {`
`    "about": "./about.md"`
`  }`
`}`

**Comment by ooodlllars** [comment]
are you trying to execute the config file

**Comment by Melil0** [comment]
host localhost

**Comment by ooodlllars** [comment]
i think rename config.js to config.json and change config.js in server.js to config.json
