### ISSUE TITLE
New install just showing blank page

### ISSUE THREAD

**Issue by lukeeexd** [seejohnrun/haste-server#306]
https://i.imgur.com/zr0maU4.png

http://195.201.149.152:7777/

**Comment by Melil0** [comment]
https://youtu.be/71VB57tEyoY

**Comment by lukeeexd** [comment]
> https://youtu.be/71VB57tEyoY

What is this?

**Comment by Melil0** [comment]
With this video you can make error-free installation.

**Comment by lukeeexd** [comment]
How haha, it’s in a different language and I have no idea what is going on in it

**Comment by Melil0** [comment]
haste-server problems in the project you can not even change the existing

**Comment by ZacMalone16** [comment]
> haste-server problems in the project you can not even change the existing

Hey, I got quite a bit working from this current reported stage of reporting, I just can't seem to get any text to be able to be typed into the website. https://p.surx.dev

**Comment by seejohnrun** [comment]
Looks like you're missing the CSS include. How are you installing?
Closing this for now since this is dated, please re-open if I can help
