### ISSUE TITLE
Can't saving document

### ISSUE THREAD

**Issue by hansputera** [seejohnrun/haste-server#307]
Can you fixed this?

**Comment by MisterFixx** [comment]
This repository is for the haste-server project, not hastebin.com, if you have issues with hastebin.com clone this project and set up your own haste server.

**Comment by hansputera** [comment]
I was cloning haste-server repository..

**Comment by MisterFixx** [comment]
Sorry, my bad, didn't realize

**Comment by predatorian3** [comment]
I am also running into this issue.

Windows 10, NodeJS 12.13.0, MSYS2. 

I cloned the Git repository, installed using `npm install`, installed missing package `npm install memcached` and it started up. However, when clicking install I get a `verbose: error adding document` and nothing else in the terminal. The web page doesn't show anything other than `Error adding document`.

**Comment by NotDonaldTrump** [comment]
> I am also running into this issue.
> 
> Windows 10, NodeJS 12.13.0, MSYS2.
> 
> I cloned the Git repository, installed using `npm install`, installed missing package `npm install memcached` and it started up. However, when clicking install I get a `verbose: error adding document` and nothing else in the terminal. The web page doesn't show anything other than `Error adding document`.

Change storage to the following:
```
 "storage": {
    "type": "file",
    "path": "./hastes"
  },
```

It will then boot up perfectly however the "hastes" will not automatically delete.

**Comment by tycrek** [comment]
> 
> Change storage to the following:
> 
> ```
>  "storage": {
>     "type": "file",
>     "path": "./hastes"
>   },
> ```
Nearly a year later I had this issue on Ubuntu 18.04. @NotDonaldTrump's fix worked for me as well.

**Comment by hansputera** [comment]
I've been fix this problem. Thanks.
