### ISSUE TITLE
Won't run on Windows

### ISSUE THREAD

**Issue by Suleman-Elahi** [seejohnrun/haste-server#309]
![image](https://user-images.githubusercontent.com/24384996/68644880-60e4b780-053c-11ea-9c4e-8330476eb613.png)

**Comment by predatorian3** [comment]
I just did:

```bash
npm install memcached
```

and the service started. However, I'm running into other issues where I can't save anything.

**Comment by NotDonaldTrump** [comment]
If you open up config.js and scroll down to "storage", change that to the following:

` 
"storage": {
    "type": "file",
    "path": "./hastes"
  },
`

It will then save the "hastes" to a folder titled "hastes" in plain text documents, your server will start right up without an issue!


Obviously still run `NPM Install` and start with **NPM start**. Only downfall with this configuration is your "hastes" will not automatically delete. 

If youre **STILL** getting errors run `NPM audit fix` followed by `NPM install` and finally `NPM start`

**Comment by robertparkerx** [comment]
I've tried those steps and still cannot save.

**Comment by seejohnrun** [comment]
If you're still experiencing these issues and would still like help please re-open this issue
