### ISSUE TITLE
Setting up haste alongside many vhosts

### ISSUE THREAD

**Issue by NotDonaldTrump** [seejohnrun/haste-server#311]
Hello,

Haste server starts up excellent, accessible via LAN, functioning perfect!

However when I attempt to port forward `7777` i get no response from canyouseeme.
Oh well, I'll try another port. No luck.

Could this be because of my many virtual apache hosts?
Any ideas?

Thanks in advance.

System:
Windows 10 Pro 1903
Xampp 3.2.3

`httpd-vhosts.conf`: https://hastebin.com/ebozositib.apache

**Comment by vwbusguy** [comment]
@NotDonaldTrump - You should setup Apache to be a reverse proxy for your virtual server to your hastebin instance running on 7777.  https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html#simple

**Comment by NotDonaldTrump** [comment]
> @NotDonaldTrump - You should setup Apache to be a reverse proxy for your virtual server to your hastebin instance running on 7777. https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html#simple

I have setup the following and still no luck. I'm confusled.
```
# Haste
<VirtualHost *:80>
    ServerName mydomain.org
    ServerAlias www.mydomain.org
    DocumentRoot "C:/xampp/htdocs/mydomain.org"
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://127.0.0.1:7777/
    ProxyPassReverse / http://127.0.0.1:7777/
</VirtualHost>
```

**Comment by NotDonaldTrump** [comment]
This is what I get when I go to the webpage:
![image](https://user-images.githubusercontent.com/42082250/71758639-b616c700-2ef6-11ea-8a3c-3deb74cc88ac.png)

**Comment by NotDonaldTrump** [comment]
My dumbass forgot to enable the http proxy module
![image](https://user-images.githubusercontent.com/42082250/71758720-79979b00-2ef7-11ea-9665-e415ff89dfa1.png)

**Comment by LoganDark** [comment]
Maybe close the issue if it's solved?
