### ISSUE TITLE
Hastebin not working

### ISSUE THREAD

**Issue by Consoli0** [seejohnrun/haste-server#321]
https://hastebin.com/ is not working properly, you can type, but saving and loading don't work.

Trying to get a raw file throws a Heroku error.

**Comment by blyatmobilebr** [comment]
I'm facing a similar problem. I can paste any code there but unfortunately I'm unable to save.

**Comment by phpjsnerd** [comment]
I think when server is handling lot more traffic it is not working.

**Comment by V-Boy** [comment]
https://hastebin.com/opayobibaj.coffeescript

everything from a previous hastebin just disappeared, anyway to get it back

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state

**Comment by SlyTheFloof** [comment]
blep

**Comment by LaraChicharo** [comment]
Same. I was going to use it to report a bug and now I encountered another bug :upside_down_face:
