### ISSUE TITLE
Getting url/key from iframe or /documents call

### ISSUE THREAD

**Issue by keremcankabadayi** [seejohnrun/haste-server#324]
Hi there!

I have same trouble with https://github.com/seejohnrun/haste-server/issues/93. I'm using iframe in Angular. How can i get document url or auto generated key?

![image](https://user-images.githubusercontent.com/23381187/83282418-390c2700-a1e2-11ea-8e73-f83117f32382.png)

**Comment by seejohnrun** [comment]
If you have the key there in the response you should be able to build a document URL from it. This is very similar to what happens in the `haste-client` repo
