### ISSUE TITLE
Custom colors?

### ISSUE THREAD

**Issue by waaberi** [seejohnrun/haste-server#326]
Is it possible for the user to define the colors for the Hastebin?
I have a key system where the key is stored in Hastebin and it says this:
`Your key is: <some kind of key here>`
`Thanks for supporting us!`
It is in a .txt format but I would like it if it was possible to add custom colors.
Also, I use the Hastebin API, not the UI.
If possible, how do I do it?

**Comment by MagicalCat1172** [comment]
![image](https://user-images.githubusercontent.com/64449816/89232735-eb72b880-d59c-11ea-9bc1-aba1f314db1b.png)
It is possible through chrome dev tools, but you would have to reset it everytime the page refreshes or when you open a new hastebin page.

**Comment by seejohnrun** [comment]
Since hastebin is meant to stay simple, I think I'm going to hold off on features like this since they're mostly about appearance. Hastebin is open source though, so you can definitely run your own fork and change the color scheme
