### ISSUE TITLE
Post a paste

### ISSUE THREAD

**Issue by Jaimss** [seejohnrun/haste-server#330]
Is there an API that I can use to post a message to the paste server that I run.

I want to be able to take messages from discord and upload them?

**Comment by AdamAtomus** [comment]
/documents
use some sort of post request

**Comment by MagicalCat1172** [comment]
I use this to post requests to hastebin through api.
https://www.npmjs.com/package/hastebin-paste

**Comment by seejohnrun** [comment]
As mentioned above you can use `curl` to post directly to `/documents`
