### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by MagicalCat1172** [seejohnrun/haste-server#332]
I am currently selfhosting, and I want to know if there is a way to be able to whitelist certain ips from rate limits.

**Comment by Mm2PL** [comment]
Use a reverse proxy like nginx. Sorry to say but this repo as it is today is dead there probably isn't going to be much added unless seejohnrun:
  a) comes back to maintain this project
  b) gives someone the power to maintain this project.

**Comment by seejohnrun** [comment]
👋  Closing this issue as resolved by @Mm2PL
