### ISSUE TITLE
hastebin doesn't work a g a i n .

### ISSUE THREAD

**Issue by mother-dearest** [seejohnrun/haste-server#337]
hi, i'm trying to paste a code into hastebin and it won't save. when i click save nothing happens. i don't know how to fix it, can you please help? 😁

**Comment by hwalker928** [comment]
I have this same issue.

**Comment by zneix** [comment]
You can try using my fork if you want which I host at https://haste.zneix.eu

**Comment by hwalker928** [comment]
I fixed the problem!

Make sure in your config you dont have memcache chosen for the data!

**Comment by twiclo** [comment]
This project is abandoned. Imo the best fork can be found here:
https://github.com/zneix/haste-server

His instance of hastebin is here:
https://haste.zneix.eu/

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
