### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by SlaSerX** [seejohnrun/haste-server#355]
Can post with curl ?

**Comment by zneix** [comment]
Use something like:

	$ curl -X POST https://hastebin.com/documents -d "content"
	{"key":"agerojacad"}

**Comment by SlaSerX** [comment]
curl -X POST https://hastebin.com/documents -d "content"
{"key":"agerojacad"}

**Comment by zneix** [comment]
Try putting the request URL into quotation marks and if you get more errors maybe try reading man page for curl.
