### ISSUE TITLE
NPM Vulnerability

### ISSUE THREAD

**Issue by guillaumearnx** [seejohnrun/haste-server#377]
Hello, there are many vulnerabilities with haste-server.

![Capture](https://user-images.githubusercontent.com/37373941/115698852-5cdddb80-a365-11eb-8bff-974fbcea8deb.PNG)

**Comment by 404invalid-user** [comment]
It's only 2 do npm audit to see which ones they are and try fixing it yourself

**Comment by guillaumearnx** [comment]
the goal being to keep your code and your dependecies up to date
