### ISSUE TITLE
Chromium grabs the shortcuts

### ISSUE THREAD

**Issue by oae** [seejohnrun/haste-server#40]
Chromium Version 24.0.1312.52 (175374) grabs shortcuts. For example if i press the ctrl +n new window opens. But haste should create new file

**Comment by Logic-gate** [comment]
Haste does create a new file(Tested on Vivaldi). The problem is that the browser is processing the shortcut before haste. This could be solved by defining a new shortcut that is unrecognizable by the browser.

**Comment by seejohnrun** [comment]
Nothing we can do here specifically if the browser or an extension is grabbing a shortcut early.  This shouldn't be the case on most browsers, and if it is can someone supply more information on platform so we can modify our shortcuts there?
