### ISSUE TITLE
Certain text input crashes browser tab when attempting to save new hastebin

### ISSUE THREAD

**Issue by stantonk** [seejohnrun/haste-server#69]
If you enter this text into hastebin and attempt to save it:

```
INFO 08-20 09:45:51,627 [main] SLF4JDemo.java,19 | marked 17 blah_blah_blah_blah completed for customerId=42 between Thu Jul 31 19:00:00 CDT 2014 and Mon Aug 04 19:00:00 CDT 2014
ERROR 08-20 09:45:51,631 [main] SLF4JDemo.java,24 | failed to mark blah_blah_blah_blah complete for customerId=42 between Thu Jul 31 19:00:00 CDT 2014 and Mon Aug 04 19:00:00 CDT 2014
```

it will completely lock up the browser tab. I suspect there is some parsing/sanitization logic that is stuck in an infinite loop...

Weird one! :-)

**Comment by mikerockett** [comment]
This appears to be happening again. I'm trying to save a PHP snippet, but Firefox and webkit/blink-based browsers are crashing.
