### ISSUE TITLE
Line numbers are not aligned with the code

### ISSUE THREAD

**Issue by ataalik** [seejohnrun/haste-server#74]
I realised line numbers are not properly aligned on some pastes. An example : http://hastebin.com/uzajafasuh.js

**Comment by seejohnrun** [comment]
I'm going to close this for now since I don't have access to the problematic code anymore. If anyone sees something like this in the wild please re-open this issue (or a new one) and we'll try to figure out where the problem is. There's a good chance things were resolved by recent upgrades as well
