### ISSUE TITLE
Ubuntu 14.04 lacks redis-server?

### ISSUE THREAD

**Issue by flasheater** [seejohnrun/haste-server#78]
I am not clear on the details, but for my Ubuntu 14.04 server I had to install redis-server via 
     apt-get install redis-server
otherwise I was getting error messages upon `npm start`.
```
# npm start

> haste@0.1.0 start /var/www/bugapaste
> node server.js

info: configuring redis
info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md
info: listening on 0.0.0.0:7766
error: error connecting to redis index 2 error=Redis connection to 0.0.0.0:6379 failed - connect ECONNREFUSED
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

The warning about the binary "node" stems from the fact, that node on Debian-derivatives is called "nodejs", but all the `package.json` files seem to hard-code the start command to "node server.js"... I have circumvented this issue by creating a symbolic link of node to nodejs on my system.

**Comment by jangrewe** [comment]
Yes, of course you need to install Redis yourself, as that's not a NPM module, or related to NodeJS at all. Just like you'll have to install Memcached, if you want to use that as a document storage. That's why it uses "file" as the default storage...

**Comment by flasheater** [comment]
Ah, now that I understand, "lacking" is indeed not appropriate. The installation instructions on the README said:
>> To use redis storage you must install the redis package in npm
  npm install redis

Since I had no nodejs experience prior, I didn't know, that this package is merely a binding to the underlying thing.

**Comment by blixnood** [comment]
The documentation is what's lacking.

**Comment by seejohnrun** [comment]
https://github.com/seejohnrun/haste-server/pull/131
