### ISSUE TITLE
Enable SSL on hastebin.com

### ISSUE THREAD

**Issue by diwu1989** [seejohnrun/haste-server#82]
Can you add cloudflare in front of hastebin.com and enable SSL?

**Comment by frdmn** [comment]
That would require @seejohnrun to buy a SSL certificate which costs money. Not sure if he is willing to do that for this project.

**Comment by didyouexpectthat** [comment]
We use nginx to display a certificate and proxy pass it to http://localhost:7777 which is our solution fo rthis.

**Comment by ApfelUser** [comment]
You can get free SSL certificates at [StartSSL](https://www.startssl.com/)

**Comment by frdmn** [comment]
I would rather suggest that @seejohnrun is looking into CloudFlare's free UniversalSSL solution which they've released two or three months ago: https://www.cloudflare.com/ssl

**Comment by ApfelUser** [comment]
@frdmn  [StartSSL](https://www.startssl.com/) is more trustworthy than [CloudFlare SSL](https://www.cloudflare.com/ssl), as this [article](https://scotthelme.co.uk/tls-conundrum-and-leaving-cloudflare/) explains.

**Comment by didyouexpectthat** [comment]
We are using StartSSL as well. It is the better option for us since we don't want CloudFlare to interfere. I've run into many problems with my websites on CloudFlare like their inability to allow me to stream large amounts of data to my sites. 
https://doc.rotten.soy for example.

**Comment by BenJule** [comment]
you can try https://letsencrypt.org/

**Comment by didyouexpectthat** [comment]
We are now using hastebin with letsencrypt. Super easy to setup scripts to keep the cert updated.

**Comment by Logic-gate** [comment]
I can confirm that LE does not cause any issues with haste. LE is being looked into as an option.

**Comment by privacytoolsIO** [comment]
Please setup a 301 redirect from

http://hastebin.com/
to
https://hastebin.com/

This came up in our current discussion here:
privacytoolsIO/privacytools.io#97

**Comment by Wohlstand** [comment]
First time I used free certs of StartSSL and wont to change to others, until I got a news that Chinese company which now owner of StartSSL, violated many rules for certificate centers and then Google and Mozilla notified about removing certs of some Centers, include StartSSL. So, I very quickly moved to letsencrypt and still use it.

**Comment by Logic-gate** [comment]
I agree with @Wohlstand; I have an instance of hastebin that uses LetsEncrypt (https://ma.tc)on my personal server...even I cant guarantee it's security on the long run. Yes the connection is safe through LetsEncrypt, other than that, I can't be 100% certain that my server has not been compromised.

**Comment by seejohnrun** [comment]
Hastebin runs behind cloudflare as of a bit ago - please re-open if there's an ongoing issue
