### ISSUE TITLE
Support word-diffs

### ISSUE THREAD

**Issue by spiffytech** [seejohnrun/haste-server#83]
Please add syntax coloring support for word diffs (`git diff --word-diff`)

**Comment by Logic-gate** [comment]
Check #108

**Comment by spiffytech** [comment]
The `.diff` extension is not compatible with word diffs, only regular diffs. I request this be reopened to track the feature request for word diffs.

**Comment by seejohnrun** [comment]
haste-server uses HLJS for highlighting, so this is probably a better issue to open over there. We just updated to the most recent version, but the `diff` mode does not at present support word diffs. This would be a great addition.

I'm going to close this for now over here
