### ISSUE TITLE
Virtual Hosts

### ISSUE THREAD

**Issue by XenRevo** [seejohnrun/haste-server#86]
How would I run this using Virtual Hosts?

**Comment by vwbusguy** [comment]
This is more of a general web server question, isn't it?  The easiest way is by using a Proxy Pass with nginx or Apache.

**Comment by XenRevo** [comment]
Yes, I was able to do that...
For anyone else that reads this here's my nginx server block

    server{
        listen 80;
        server_name your.domain.name;

        root /var/www/dir;

        location / {
              proxy_pass http://localhost:4578; ##Change "4578" to the port you use.
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            include fastcgi_params;
        }

        error_page 500 403 404 /500.html;
        location = /500.html {
            root  /var/www/err;
        }

    }

**Comment by vwbusguy** [comment]
There's no php in haste server, so no need for php-fpm.

**Comment by XenRevo** [comment]
Modified to remove unnecessary things
