### ISSUE TITLE
Line numbers stop prematurely

### ISSUE THREAD

**Issue by seejohnrun** [seejohnrun/haste-server#88]
For some reason, only first 2114 lines are numbered (see for yourself), and I did not see a feedback address to report the bug properly.

**Comment by yonas** [comment]
I can't reproduce this.

**Comment by Logic-gate** [comment]
Couldn't reproduce it. 

![screenshot from 2016-08-25 21-51-57](https://cloud.githubusercontent.com/assets/2302251/17981874/3435d690-6b0e-11e6-8311-afe8fb07c717.png)
