### ISSUE TITLE
Suggestion: Use first line to decide syntax

### ISSUE THREAD

**Issue by f3bruary** [seejohnrun/haste-server#89]
I notice every now and then the syntax prediction is wrong. It's fine by me, I don't really mind, but I thought it might help if you take the first line of a paste into the whole 'prediction algorithm' for syntaxes. I just pasted a bash script (first line is #!/bin/bash) and it assigned .rb as syntax.

**Comment by moomoohk** [comment]
The extension in the URL is what determines the syntax highlighting. If the automatic prediction is wrong you can just override it yourself.

(Although having shebangs would be nice)

**Comment by Xaekai** [comment]
It would be nice if that detail was mentioned in the README.md somewhere

**Comment by Logic-gate** [comment]
Will add a note on README about this. Thanks @moomoohk.
