### ISSUE TITLE
In locked haste appears horizontal scroll bar in browser

### ISSUE THREAD

**Issue by ogarcia** [seejohnrun/haste-server#91]
Hi,

If you edit something and saves it, in the locked view appears an horizontal scroll bar in browser, as attached screenshot:
![image](https://cloud.githubusercontent.com/assets/572924/9277326/9c781620-42a9-11e5-98aa-33ff154eae97.png)

I think that is for this CSS line: https://github.com/seejohnrun/haste-server/blob/master/static/application.css#L41

If you remove the `width: 100%;` into `#box` block seems fix issue.

**Comment by Logic-gate** [comment]
Thanks. Will look into this.

**Comment by Qwerty-Space** [comment]
Was there ever a solution to this?

**Comment by Qwerty-Space** [comment]
Oh

**Comment by Qwerty-Space** [comment]
No that doesn't fix it.  But I have found a "fix"

**Comment by seejohnrun** [comment]
I'm unable to reproduce this in the latest version of hastebin after upgrading dependent libraries. In addition, #351 will soon update and modernize a bunch of the CSS which should clear issues like this up.

If anyone has an example of text that reproduces this please re-open so we can get it fixed. Thank you!
