### ISSUE TITLE
suggestion; copy link to clipboard

### ISSUE THREAD

**Issue by SobieskiCodes** [seejohnrun/haste-server#93]
I don't use twitter and would like to keep hastebin in an "iframe" for use on our forums, but in an iframe you can't copy the url, how can i "copy to clipboard" with a button click?

**Comment by Dasoren** [comment]
It "could" be done, but there is no good way of doing that. Mostly due to browser security settings that can not be easily edited. If you are going to have it in a iframe you are going to have to use a button or ctrl-c/ctrl-v

**Comment by Logic-gate** [comment]
As @Dasoren stated, the simplest way is to copy/paste manually. You could also use the client and pipe  directly to hastebin, it will return the URL.

**Comment by keremcankabadayi** [comment]
Hi there, I'm from future, I'm trying to get the url from iframe as mentioned above. Any modern solution for this? I'm coding with angular 9.
