### ISSUE TITLE
Possibility of One Time Secrets?

### ISSUE THREAD

**Issue by Prophecy67** [seejohnrun/haste-server#96]
Wondering if and how there is a possibility to build in a functionality to drop a redis key (DEL key) after viewing sent URL. This could push haste in to transfering notes relatively securely without having to put the deletion timer really strict.

**Comment by Dasoren** [comment]
I have support for this added into my version of haste. If this is something wanted by you, I could push it to github for you to look at. I have also added support for many other things as well.

**Comment by Prophecy67** [comment]
@Dasoren Would be lovely to look at.. Especially if it is a library i can include.

**Comment by Logic-gate** [comment]
Thanks @Dasoren. Haste is all about simplicity. Although that's a great idea, and @Dasoren already incorporated it, It will probably not be added here.
