### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by simpleuser99** [seejohnrun/haste-server#97]
Hello.
I have the next  issue:

> npm start
> 
> haste@0.1.0 start /home/user/fsapp/haste/haste-server-master
> node server.js
> 
> /home/user/fsapp/haste/haste-server->master/node_modules/connect/node_modules/qs/lib/index.js:5
> const Stringify = require('./stringify');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>    at Module._compile (module.js:439:25)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>   at Function.Module._load (module.js:312:12)
>    at Module.require (module.js:364:17)
>    at require (module.js:380:17)
>    at Object.<anonymous> (/home/user/fsapp/haste/haste-server->master/node_modules/connect/lib/middleware/bodyParser.js:13:10)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
> npm ERR! weird error 8
> npm ERR! not ok code 0

My nodejs version is 0.10.36.
CentOs 6.7
How can i fix it?

**Comment by wraithgar** [comment]
connect `1.9.2` is requiring `qs >=0.4.0`, which means *anything* greater than `0.4.0`.  This is pulling in the very latest `qs` which is `6.0.0` and requires npm `v4.0.0` or greater.  Fixing this locally would either require a patch to that very old version of connect, or you can try installing an older version of `qs` before you install `connect` locally.

**Comment by simpleuser99** [comment]
ok. I install qs ver 2.2.2 and i have next messages:

 npm start

> haste@0.1.0 start /home/admin7/fsapp/haste/haste-server-master
> node server.js

>info: configuring redis
>info: compressed application.js into application.min.js
>info: loading static document name=about, path=./about.md
>info: listening on 0.0.0.0:7777
>error: error connecting to redis index 2 error=Redis connection to 0.0.0.0:6379 failed - connect >ECONNREFUSED
>npm ERR! weird error 1
>npm ERR! not ok code 0

**Comment by gramakri** [comment]
Using node 4.2.1, makes it work. Using node 0.10.x gives this error (for reasons @wraithgar pointed out)

**Comment by postblue** [comment]
0.10.x is the default in Debian Jessie, and I don't want to mess with my server for just this one service (Etherpad and Ghost are fine with it). Isn't it possible to fixe it?
